<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2023-11-23">

<title>ISSS624 - Hands-On Ex 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS624</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-ex" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Hands-On Ex</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-ex">    
        <li>
    <a class="dropdown-item" href="../../HandsOnEx/HandsOnEx1/handson_ex1.html" rel="" target="">
 <span class="dropdown-text">Hands-On Ex 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../HandsOnEx/HandsOnEx2/handsonex2.html" rel="" target="">
 <span class="dropdown-text">Hands-On Ex 2</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-ex" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">In-Class Ex</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-ex">    
        <li>
    <a class="dropdown-item" href="../../InClassEx/Ex01/inclass_Ex01.html" rel="" target="">
 <span class="dropdown-text">In-Class Ex 01</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a>
  <ul class="collapse">
  <li><a href="#the-study-area-and-data" id="toc-the-study-area-and-data" class="nav-link" data-scroll-target="#the-study-area-and-data">The Study Area and Data</a></li>
  <li><a href="#loading-the-packages" id="toc-loading-the-packages" class="nav-link" data-scroll-target="#loading-the-packages">Loading the Packages</a></li>
  </ul></li>
  <li><a href="#getting-the-data-ready" id="toc-getting-the-data-ready" class="nav-link" data-scroll-target="#getting-the-data-ready">Getting the data ready</a>
  <ul class="collapse">
  <li><a href="#performing-relational-join" id="toc-performing-relational-join" class="nav-link" data-scroll-target="#performing-relational-join">Performing relational join</a></li>
  <li><a href="#visualising-the-data---regional-development-indicator" id="toc-visualising-the-data---regional-development-indicator" class="nav-link" data-scroll-target="#visualising-the-data---regional-development-indicator">Visualising the Data - Regional Development Indicator</a></li>
  </ul></li>
  <li><a href="#computing-contiguity-spatial-weights" id="toc-computing-contiguity-spatial-weights" class="nav-link" data-scroll-target="#computing-contiguity-spatial-weights">Computing Contiguity Spatial Weights</a>
  <ul class="collapse">
  <li><a href="#overview-of-contiguity-spatial-weights" id="toc-overview-of-contiguity-spatial-weights" class="nav-link" data-scroll-target="#overview-of-contiguity-spatial-weights">Overview of Contiguity Spatial Weights</a></li>
  <li><a href="#compute-queen-contiguity-based-neighbours" id="toc-compute-queen-contiguity-based-neighbours" class="nav-link" data-scroll-target="#compute-queen-contiguity-based-neighbours">Compute QUEEN contiguity based neighbours</a></li>
  <li><a href="#computing-rook-contiguity-based-neighbours" id="toc-computing-rook-contiguity-based-neighbours" class="nav-link" data-scroll-target="#computing-rook-contiguity-based-neighbours">Computing ROOK contiguity based neighbours</a></li>
  <li><a href="#visualising-contiguity-weights" id="toc-visualising-contiguity-weights" class="nav-link" data-scroll-target="#visualising-contiguity-weights">Visualising contiguity weights</a>
  <ul class="collapse">
  <li><a href="#plotting-queen-map" id="toc-plotting-queen-map" class="nav-link" data-scroll-target="#plotting-queen-map">Plotting QUEEN map</a></li>
  <li><a href="#plotting-rook-map" id="toc-plotting-rook-map" class="nav-link" data-scroll-target="#plotting-rook-map">Plotting ROOK map</a></li>
  <li><a href="#plotting-both-queen-and-rook-maps" id="toc-plotting-both-queen-and-rook-maps" class="nav-link" data-scroll-target="#plotting-both-queen-and-rook-maps">Plotting both QUEEN and ROOK maps</a></li>
  </ul></li>
  <li><a href="#computing-distance-based-neighbours" id="toc-computing-distance-based-neighbours" class="nav-link" data-scroll-target="#computing-distance-based-neighbours">Computing distance based neighbours</a>
  <ul class="collapse">
  <li><a href="#determine-the-cut-off-distance" id="toc-determine-the-cut-off-distance" class="nav-link" data-scroll-target="#determine-the-cut-off-distance">Determine the cut-off distance</a></li>
  <li><a href="#computing-fixed-distance-weight-matrix" id="toc-computing-fixed-distance-weight-matrix" class="nav-link" data-scroll-target="#computing-fixed-distance-weight-matrix">Computing fixed distance weight matrix</a></li>
  <li><a href="#plotting-fixed-distance-weight-matrix" id="toc-plotting-fixed-distance-weight-matrix" class="nav-link" data-scroll-target="#plotting-fixed-distance-weight-matrix">Plotting fixed distance weight matrix</a></li>
  </ul></li>
  <li><a href="#computing-adaptive-distance-weight-matrix" id="toc-computing-adaptive-distance-weight-matrix" class="nav-link" data-scroll-target="#computing-adaptive-distance-weight-matrix">Computing adaptive distance weight matrix</a>
  <ul class="collapse">
  <li><a href="#plotting-distance-based-neighbours" id="toc-plotting-distance-based-neighbours" class="nav-link" data-scroll-target="#plotting-distance-based-neighbours">Plotting distance based neighbours</a></li>
  </ul></li>
  <li><a href="#weights-based-on-inverse-distance-weighting" id="toc-weights-based-on-inverse-distance-weighting" class="nav-link" data-scroll-target="#weights-based-on-inverse-distance-weighting">Weights based on Inverse Distance Weighting</a>
  <ul class="collapse">
  <li><a href="#row-standardised-weights-matrix" id="toc-row-standardised-weights-matrix" class="nav-link" data-scroll-target="#row-standardised-weights-matrix">Row-standardised weights matrix</a></li>
  </ul></li>
  <li><a href="#application-of-spatial-weight-matrix" id="toc-application-of-spatial-weight-matrix" class="nav-link" data-scroll-target="#application-of-spatial-weight-matrix">Application of Spatial Weight Matrix</a>
  <ul class="collapse">
  <li><a href="#spatial-lag-with-row-standardised-weights" id="toc-spatial-lag-with-row-standardised-weights" class="nav-link" data-scroll-target="#spatial-lag-with-row-standardised-weights">Spatial lag with row-standardised weights</a></li>
  <li><a href="#spatial-lag-as-a-sum-of-neighbouring-values" id="toc-spatial-lag-as-a-sum-of-neighbouring-values" class="nav-link" data-scroll-target="#spatial-lag-as-a-sum-of-neighbouring-values">Spatial lag as a sum of neighbouring values</a></li>
  <li><a href="#spatial-window-average" id="toc-spatial-window-average" class="nav-link" data-scroll-target="#spatial-window-average">Spatial window average</a></li>
  <li><a href="#spatial-window-sum" id="toc-spatial-window-sum" class="nav-link" data-scroll-target="#spatial-window-sum">Spatial window sum</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hands-On Ex 2</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 23, 2023</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">November 23, 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="overview" class="level1">
<h1>Overview</h1>
<p>In this hands-on exercise, we will learn how to compute spatial weights using R. By the end to this hands-on exercise, we will be able to:</p>
<ul>
<li><p>import geospatial data using appropriate function(s) of <strong>sf</strong> package,</p></li>
<li><p>import csv file using appropriate function of <strong>readr</strong> package,</p></li>
<li><p>perform relational join using appropriate join function of <strong>dplyr</strong> package,</p></li>
<li><p>compute spatial weights using appropriate functions of <strong>spdep</strong> package, and</p></li>
<li><p>calculate spatially lagged variables using appropriate functions of <strong>spdep</strong> package.</p></li>
</ul>
<section id="the-study-area-and-data" class="level2">
<h2 class="anchored" data-anchor-id="the-study-area-and-data">The Study Area and Data</h2>
<p>We will be using the following data sets:</p>
<ul>
<li><p>Geospatial Data: Hunan County Boundary Layer</p></li>
<li><p>Aspatial Data: Hunan’s local development indicators in 2012. Hunan_2012.csv</p></li>
</ul>
</section>
<section id="loading-the-packages" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-packages">Loading the Packages</h2>
<p>We will be using the following packages for this exercise:</p>
<p>New package for this exercise - <strong>spdep</strong></p>
<p>The <strong>spdep package</strong> is a collection of functions for spatial data analysis in R. It provides tools for creating spatial weights matrices, performing spatial autocorrelation tests, and fitting spatial regression models. The package is widely used in a variety of fields, including geography, economics, and ecology.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, spdep, tmap, tidyverse, knitr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="getting-the-data-ready" class="level1">
<h1>Getting the data ready</h1>
<p>First - we will import the data.</p>
<p>We will start with the geospatial data - Hunan county, which is in ESRI shapefile format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>hunan <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>, </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">layer =</span> <span class="st">"Hunan"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `Hunan' from data source 
  `C:\zjjgithubb\ISSS624\HandsOnEx\HandsOnEx2\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 88 features and 7 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p>Next, we will import the aspatial data using the readr package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>hunan2012 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/Hunan_2012.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Quick check on the data to learn more about the data. It lists the County name and the various indicators.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hunan2012)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 x 29
  County City  avg_wage deposite   FAI Gov_Rev Gov_Exp    GDP GDPPC    GIO  Loan
  &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 Anhua  Yiya~    30544   10967  6832.    457.   2703  13225  14567  9277. 3955.
2 Anren  Chen~    28058    4599. 6386.    221.   1455.  4941. 12761  4189. 2555.
3 Anxia~ Chan~    31935    5517. 3541     244.   1780. 12482  23667  5109. 2807.
4 Baoji~ Huna~    30843    2250  1005.    193.   1379.  4088. 14563  3624. 1254.
5 Chali~ Zhuz~    31251    8241. 6508.    620.   1947  11585  20078  9158. 4287.
6 Chang~ Heng~    28518   10860  7920     770.   2632. 19886  24418 37392  4243.
# i 18 more variables: NIPCR &lt;dbl&gt;, Bed &lt;dbl&gt;, Emp &lt;dbl&gt;, EmpR &lt;dbl&gt;,
#   EmpRT &lt;dbl&gt;, Pri_Stu &lt;dbl&gt;, Sec_Stu &lt;dbl&gt;, Household &lt;dbl&gt;,
#   Household_R &lt;dbl&gt;, NOIP &lt;dbl&gt;, Pop_R &lt;dbl&gt;, RSCG &lt;dbl&gt;, Pop_T &lt;dbl&gt;,
#   Agri &lt;dbl&gt;, Service &lt;dbl&gt;, Disp_Inc &lt;dbl&gt;, RORP &lt;dbl&gt;, ROREmp &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="performing-relational-join" class="level2">
<h2 class="anchored" data-anchor-id="performing-relational-join">Performing relational join</h2>
<p>We will update the attribute table update the attribute table of&nbsp;<em>hunan</em>'s SpatialPolygonsDataFrame with the attribute fields of&nbsp;<em>hunan2012</em>&nbsp;dataframe. This is performed by using&nbsp;<em>left_join()</em>&nbsp;of&nbsp;<strong>dplyr</strong>&nbsp;package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>hunan <span class="ot">&lt;-</span> <span class="fu">left_join</span>(hunan,hunan2012)<span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">7</span>, <span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="1">
<li><p><strong><code>left_join(hunan, hunan2012)</code></strong>: This line performs a left join between the data frames <strong><code>hunan</code></strong> and <strong><code>hunan2012</code></strong>. The left join includes all rows from the <strong><code>hunan</code></strong> data frame and the matching rows from the <strong><code>hunan2012</code></strong> data frame based on a common key or keys. The result is a data frame with columns from both data frames.</p></li>
<li><p><strong><code>%&gt;%</code></strong>: The pipe operator (<strong><code>%&gt;%</code></strong>) is used to pass the result of the left join to the next operation.</p></li>
<li><p><strong><code>select(1:4, 7, 15)</code></strong>: This line selects specific columns from the joined data frame. Columns 1 through 4, column 7, and column 15 are retained in the final data frame, and the rest are dropped.</p></li>
</ol>
</section>
<section id="visualising-the-data---regional-development-indicator" class="level2">
<h2 class="anchored" data-anchor-id="visualising-the-data---regional-development-indicator">Visualising the Data - Regional Development Indicator</h2>
<p>We will prepare a base map and a choropleth map showing the distribution of GDPPC 2012 by using&nbsp;<em>qtm()</em>&nbsp;of&nbsp;<strong>tmap</strong>&nbsp;package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>basemap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(hunan) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_text</span>(<span class="st">"NAME_3"</span>, <span class="at">size=</span><span class="fl">0.5</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"GDPPC"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(basemap, gdppc, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="handsonex2_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="computing-contiguity-spatial-weights" class="level1">
<h1>Computing Contiguity Spatial Weights</h1>
<section id="overview-of-contiguity-spatial-weights" class="level2">
<h2 class="anchored" data-anchor-id="overview-of-contiguity-spatial-weights">Overview of Contiguity Spatial Weights</h2>
<p>In spatial analysis, contiguity spatial weights represent the connections or relationships between spatial units, such as regions, countries, or points on a map. These weights are typically constructed based on the geometric proximity of the units, indicating whether they share a common border or are within a certain distance of each other. The specific type of contiguity used depends on the research question and the nature of the data.</p>
<p><strong>Types of Contiguity Spatial Weights</strong></p>
<p>There are two main types of contiguity spatial weights:</p>
<ol type="1">
<li><p><strong>Rook contiguity:</strong> Units are considered neighbors if they share a common edge.</p></li>
<li><p><strong>Queen contiguity:</strong> Units are considered neighbors if they share a common edge or vertex.</p></li>
</ol>
<p>These two types of contiguity differ in how they define connectivity. Rook contiguity is more restrictive, while queen contiguity is more inclusive. The choice of contiguity weight depends on the specific application and the research question.</p>
<p><strong>Applications of Contiguity Spatial Weights</strong></p>
<p>Contiguity spatial weights are used in various spatial analysis applications, including:</p>
<ol type="1">
<li><p><strong>Spatial autocorrelation analysis:</strong> Identifying patterns of similarity or dissimilarity in spatial data.</p></li>
<li><p><strong>Spatial regression modeling:</strong> Accounting for spatial dependence in statistical models.</p></li>
<li><p><strong>Spatial interpolation:</strong> Estimating values at unsampled locations based on surrounding values.</p></li>
<li><p><strong>Spatial diffusion modeling:</strong> Analyzing the spread of phenomena over space and time.</p></li>
</ol>
<p><strong>Construction of Contiguity Spatial Weights</strong></p>
<p>Contiguity spatial weights are typically constructed using spatial data structures and algorithms. These tools allow for efficient and accurate identification of neighbors based on geometric proximity. The specific construction method depends on the type of spatial data (polygons, points, lines) and the type of contiguity (rook or queen).</p>
<p><strong>Normalization of Contiguity Spatial Weights</strong></p>
<p>Contiguity spatial weights are often normalized to ensure that they are comparable across different spatial units and studies. Normalization methods can involve row-standardization, column-standardization, or other techniques.</p>
<p><strong>Importance of Contiguity Spatial Weights</strong></p>
<p>Contiguity spatial weights play a crucial role in spatial analysis by providing a formal representation of spatial relationships between units. They allow researchers to incorporate spatial dependence into statistical models and analyze the impact of spatial context on various phenomena.</p>
</section>
<section id="compute-queen-contiguity-based-neighbours" class="level2">
<h2 class="anchored" data-anchor-id="compute-queen-contiguity-based-neighbours">Compute QUEEN contiguity based neighbours</h2>
<p>Computing the Queen contiguity weight matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(hunan, <span class="at">queen=</span><span class="cn">TRUE</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 448 
Percentage nonzero weights: 5.785124 
Average number of links: 5.090909 
Link number distribution:

 1  2  3  4  5  6  7  8  9 11 
 2  2 12 16 24 14 11  4  2  1 
2 least connected regions:
30 65 with 1 link
1 most connected region:
85 with 11 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 88 area units in Hunan. The most connected area unit has 11 neighbours. There are two area units with only one heighbours.</p>
<p>For each polygon in our polygon object, <em>wm_q</em> lists all neighboring polygons. For example, to see the neighbors for the first polygon in the object, type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>wm_q[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2  3  4 57 85</code></pre>
</div>
</div>
<p>Polygon 1 has 5 neighbors. The numbers represent the polygon IDs as stored in hunan SpatialPolygonsDataFrame class.</p>
<p>We can retrive the county name of Polygon ID=1 by using the code chunk below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>hunan<span class="sc">$</span>County[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Anxiang"</code></pre>
</div>
</div>
<p>The output reveals that Polygon ID=1 is Anxiang county.</p>
<p>To reveal the county names of the five neighboring polygons, the code chunk will be used:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>hunan<span class="sc">$</span>NAME_3[<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">57</span>,<span class="dv">85</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Hanshou" "Jinshi"  "Li"      "Nan"     "Taoyuan"</code></pre>
</div>
</div>
<p>We can retrieve the GDPPC of these five countries by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>nb1 <span class="ot">&lt;-</span> wm_q[[<span class="dv">1</span>]]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>nb1 <span class="ot">&lt;-</span> hunan<span class="sc">$</span>GDPPC[nb1]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>nb1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20981 34592 24473 21311 22879</code></pre>
</div>
</div>
<p>The printed output above shows that the GDPPC of the five nearest neighbours based on Queen's method are 20981, 34592, 24473, 21311 and 22879 respectively.</p>
<p>We can display the complete weight matrix by using <em>str()</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 88
 $ : int [1:5] 2 3 4 57 85
 $ : int [1:5] 1 57 58 78 85
 $ : int [1:4] 1 4 5 85
 $ : int [1:4] 1 3 5 6
 $ : int [1:4] 3 4 6 85
 $ : int [1:5] 4 5 69 75 85
 $ : int [1:4] 67 71 74 84
 $ : int [1:7] 9 46 47 56 78 80 86
 $ : int [1:6] 8 66 68 78 84 86
 $ : int [1:8] 16 17 19 20 22 70 72 73
 $ : int [1:3] 14 17 72
 $ : int [1:5] 13 60 61 63 83
 $ : int [1:4] 12 15 60 83
 $ : int [1:3] 11 15 17
 $ : int [1:4] 13 14 17 83
 $ : int [1:5] 10 17 22 72 83
 $ : int [1:7] 10 11 14 15 16 72 83
 $ : int [1:5] 20 22 23 77 83
 $ : int [1:6] 10 20 21 73 74 86
 $ : int [1:7] 10 18 19 21 22 23 82
 $ : int [1:5] 19 20 35 82 86
 $ : int [1:5] 10 16 18 20 83
 $ : int [1:7] 18 20 38 41 77 79 82
 $ : int [1:5] 25 28 31 32 54
 $ : int [1:5] 24 28 31 33 81
 $ : int [1:4] 27 33 42 81
 $ : int [1:3] 26 29 42
 $ : int [1:5] 24 25 33 49 54
 $ : int [1:3] 27 37 42
 $ : int 33
 $ : int [1:8] 24 25 32 36 39 40 56 81
 $ : int [1:8] 24 31 50 54 55 56 75 85
 $ : int [1:5] 25 26 28 30 81
 $ : int [1:3] 36 45 80
 $ : int [1:6] 21 41 47 80 82 86
 $ : int [1:6] 31 34 40 45 56 80
 $ : int [1:4] 29 42 43 44
 $ : int [1:4] 23 44 77 79
 $ : int [1:5] 31 40 42 43 81
 $ : int [1:6] 31 36 39 43 45 79
 $ : int [1:6] 23 35 45 79 80 82
 $ : int [1:7] 26 27 29 37 39 43 81
 $ : int [1:6] 37 39 40 42 44 79
 $ : int [1:4] 37 38 43 79
 $ : int [1:6] 34 36 40 41 79 80
 $ : int [1:3] 8 47 86
 $ : int [1:5] 8 35 46 80 86
 $ : int [1:5] 50 51 52 53 55
 $ : int [1:4] 28 51 52 54
 $ : int [1:5] 32 48 52 54 55
 $ : int [1:3] 48 49 52
 $ : int [1:5] 48 49 50 51 54
 $ : int [1:3] 48 55 75
 $ : int [1:6] 24 28 32 49 50 52
 $ : int [1:5] 32 48 50 53 75
 $ : int [1:7] 8 31 32 36 78 80 85
 $ : int [1:6] 1 2 58 64 76 85
 $ : int [1:5] 2 57 68 76 78
 $ : int [1:4] 60 61 87 88
 $ : int [1:4] 12 13 59 61
 $ : int [1:7] 12 59 60 62 63 77 87
 $ : int [1:3] 61 77 87
 $ : int [1:4] 12 61 77 83
 $ : int [1:2] 57 76
 $ : int 76
 $ : int [1:5] 9 67 68 76 84
 $ : int [1:4] 7 66 76 84
 $ : int [1:5] 9 58 66 76 78
 $ : int [1:3] 6 75 85
 $ : int [1:3] 10 72 73
 $ : int [1:3] 7 73 74
 $ : int [1:5] 10 11 16 17 70
 $ : int [1:5] 10 19 70 71 74
 $ : int [1:6] 7 19 71 73 84 86
 $ : int [1:6] 6 32 53 55 69 85
 $ : int [1:7] 57 58 64 65 66 67 68
 $ : int [1:7] 18 23 38 61 62 63 83
 $ : int [1:7] 2 8 9 56 58 68 85
 $ : int [1:7] 23 38 40 41 43 44 45
 $ : int [1:8] 8 34 35 36 41 45 47 56
 $ : int [1:6] 25 26 31 33 39 42
 $ : int [1:5] 20 21 23 35 41
 $ : int [1:9] 12 13 15 16 17 18 22 63 77
 $ : int [1:6] 7 9 66 67 74 86
 $ : int [1:11] 1 2 3 5 6 32 56 57 69 75 ...
 $ : int [1:9] 8 9 19 21 35 46 47 74 84
 $ : int [1:4] 59 61 62 88
 $ : int [1:2] 59 87
 - attr(*, "class")= chr "nb"
 - attr(*, "region.id")= chr [1:88] "1" "2" "3" "4" ...
 - attr(*, "call")= language poly2nb(pl = hunan, queen = TRUE)
 - attr(*, "type")= chr "queen"
 - attr(*, "sym")= logi TRUE</code></pre>
</div>
</div>
</section>
<section id="computing-rook-contiguity-based-neighbours" class="level2">
<h2 class="anchored" data-anchor-id="computing-rook-contiguity-based-neighbours">Computing ROOK contiguity based neighbours</h2>
<p>The code chunk below is used to compute Rook contiguity weight matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>wm_r <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(hunan, <span class="at">queen=</span><span class="cn">FALSE</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wm_r)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 440 
Percentage nonzero weights: 5.681818 
Average number of links: 5 
Link number distribution:

 1  2  3  4  5  6  7  8  9 10 
 2  2 12 20 21 14 11  3  2  1 
2 least connected regions:
30 65 with 1 link
1 most connected region:
85 with 10 links</code></pre>
</div>
</div>
<p>The summary report above shows that there are 88 area units in Hunan. The most connect area unit has 10 neighbours. There are two area units with only one neighbours.</p>
</section>
<section id="visualising-contiguity-weights" class="level2">
<h2 class="anchored" data-anchor-id="visualising-contiguity-weights">Visualising contiguity weights</h2>
<p>A connectivity graph takes a point and displays a line to each neighboring point. We are working with polygons at the moment, so we will need to get points in order to make our connectivity graphs. The most typically method for this will be polygon centroids. We will calculate these in the sf package before moving onto the graphs. Getting Latitude and Longitude of Polygon Centroids</p>
<p>We will need points to associate with each polygon before we can make our connectivity graph. It will be a little more complicated than just running st_centroid on the sf object: us.bound. We need the coordinates in a separate data frame for this to work. To do this we will use a mapping function. The mapping function applies a given function to each element of a vector and returns a vector of the same length. Our input vector will be the geometry column of us.bound. Our function will be st_centroid. We will be using map_dbl variation of map from the purrr package. For more documentation, check out map documentation</p>
<p>To get our longitude values we map the st_centroid function over the geometry column of us.bound and access the longitude value through double bracket notation [[]] and 1. This allows us to get only the longitude, which is the first value in each centroid.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>longitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(hunan<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We do the same for latitude with one key difference. We access the second value per each centroid with [[2]].</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>latitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(hunan<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">2</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that we have latitude and longitude, we use cbind to put longitude and latitude into the same object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">cbind</span>(longitude, latitude)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We check to see if things are formatted correctly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     longitude latitude
[1,]  112.1531 29.44362
[2,]  112.0372 28.86489
[3,]  111.8917 29.47107
[4,]  111.7031 29.74499
[5,]  111.6138 29.49258
[6,]  111.0341 29.79863</code></pre>
</div>
</div>
<section id="plotting-queen-map" class="level3">
<h3 class="anchored" data-anchor-id="plotting-queen-map">Plotting QUEEN map</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_q, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col=</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="handsonex2_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="plotting-rook-map" class="level3">
<h3 class="anchored" data-anchor-id="plotting-rook-map">Plotting ROOK map</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_r, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="handsonex2_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="plotting-both-queen-and-rook-maps" class="level3">
<h3 class="anchored" data-anchor-id="plotting-both-queen-and-rook-maps">Plotting both QUEEN and ROOK maps</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"Queen Contiguity"</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_q, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col=</span> <span class="st">"red"</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"Rook Contiguity"</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_r, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="handsonex2_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="computing-distance-based-neighbours" class="level2">
<h2 class="anchored" data-anchor-id="computing-distance-based-neighbours">Computing distance based neighbours</h2>
<p>In this section, you will learn how to derive distance-based weight matrices by using <a href="https://r-spatial.github.io/spdep/reference/dnearneigh.html"><em>dnearneigh()</em></a> of <strong>spdep</strong> package.</p>
<p>The function identifies neighbours of region points by Euclidean distance with a distance band with lower d1= and upper d2= bounds controlled by the bounds= argument. If unprojected coordinates are used and either specified in the coordinates object x or with x as a two column matrix and longlat=TRUE, great circle distances in <strong>km</strong> will be calculated assuming the WGS84 reference ellipsoid.</p>
<section id="determine-the-cut-off-distance" class="level3">
<h3 class="anchored" data-anchor-id="determine-the-cut-off-distance">Determine the cut-off distance</h3>
<p>Firstly, we need to determine the upper limit for distance band by using the steps below:</p>
<ul>
<li><p>Return a matrix with the indices of points belonging to the set of the k nearest neighbours of each other by using <a href="https://r-spatial.github.io/spdep/reference/knearneigh.html"><em>knearneigh()</em></a> of <strong>spdep</strong>.</p></li>
<li><p>Convert the knn object returned by <em>knearneigh()</em> into a neighbours list of class nb with a list of integer vectors containing neighbour region number ids by using <a href="https://r-spatial.github.io/spdep/reference/knn2nb.html"><em>knn2nb()</em></a>.</p></li>
<li><p>Return the length of neighbour relationship edges by using <a href="https://r-spatial.github.io/spdep/reference/nbdists.html"><em>nbdists()</em></a> of <strong>spdep</strong>. The function returns in the units of the coordinates if the coordinates are projected, in km otherwise.</p></li>
<li><p>Remove the list structure of the returned object by using <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/unlist"><strong>unlist()</strong></a>.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#coords &lt;- coordinates(hunan)</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>k1 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords))</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>k1dists <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">nbdists</span>(k1, coords, <span class="at">longlat =</span> <span class="cn">TRUE</span>))</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(k1dists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  24.79   32.57   38.01   39.07   44.52   61.79 </code></pre>
</div>
</div>
<p>The summary report shows that the largest first nearest neighbour distance is 61.79 km, so using this as the upper threshold gives certainty that all units will have at least one neighbour.</p>
</section>
<section id="computing-fixed-distance-weight-matrix" class="level3">
<h3 class="anchored" data-anchor-id="computing-fixed-distance-weight-matrix">Computing fixed distance weight matrix</h3>
<p>Now, we will compute the distance weight matrix by using&nbsp;<em>dnearneigh()</em>&nbsp;as shown in the code chunk below.</p>
<p>dnearneigh(your_spatial_data, d1 = distance_threshold, longlat = FALSE) - <strong><code>dnearneigh</code></strong>: This function from the <strong><code>spdep</code></strong> package creates a neighbors list based on a specified distance threshold (<strong><code>d1</code></strong>). The <strong><code>longlat</code></strong> parameter is set to <strong><code>FALSE</code></strong> because it assumes the data is in planar coordinates. But we are using longlat so it is set to TRUE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>wm_d62 <span class="ot">&lt;-</span> <span class="fu">dnearneigh</span>(coords, <span class="dv">0</span>, <span class="dv">62</span>, <span class="at">longlat =</span> <span class="cn">TRUE</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>wm_d62</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 324 
Percentage nonzero weights: 4.183884 
Average number of links: 3.681818 </code></pre>
</div>
</div>
<ul>
<li><p><strong>Number of regions:</strong> There are 88 regions in your spatial data.</p></li>
<li><p><strong>Number of nonzero links:</strong> The total number of links or connections between regions is 324.</p></li>
<li><p><strong>Percentage nonzero weights:</strong> This is the percentage of nonzero weights in the spatial weights matrix. In your case, it’s 4.183884%, indicating that a small percentage of all possible pairwise connections have been defined as neighbors.</p></li>
<li><p><strong>Average number of links:</strong> On average, each region has approximately 3.68 links or neighbors.</p></li>
</ul>
<p>Next, we will use&nbsp;<em>str()</em>&nbsp;to display the content of wm_d62 weight matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(wm_d62)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 88
 $ : int [1:5] 3 4 5 57 64
 $ : int [1:4] 57 58 78 85
 $ : int [1:4] 1 4 5 57
 $ : int [1:3] 1 3 5
 $ : int [1:4] 1 3 4 85
 $ : int 69
 $ : int [1:2] 67 84
 $ : int [1:4] 9 46 47 78
 $ : int [1:4] 8 46 68 84
 $ : int [1:4] 16 22 70 72
 $ : int [1:3] 14 17 72
 $ : int [1:5] 13 60 61 63 83
 $ : int [1:4] 12 15 60 83
 $ : int [1:2] 11 17
 $ : int 13
 $ : int [1:4] 10 17 22 83
 $ : int [1:3] 11 14 16
 $ : int [1:3] 20 22 63
 $ : int [1:5] 20 21 73 74 82
 $ : int [1:5] 18 19 21 22 82
 $ : int [1:6] 19 20 35 74 82 86
 $ : int [1:4] 10 16 18 20
 $ : int [1:3] 41 77 82
 $ : int [1:4] 25 28 31 54
 $ : int [1:4] 24 28 33 81
 $ : int [1:4] 27 33 42 81
 $ : int [1:2] 26 29
 $ : int [1:6] 24 25 33 49 52 54
 $ : int [1:2] 27 37
 $ : int 33
 $ : int [1:2] 24 36
 $ : int 50
 $ : int [1:5] 25 26 28 30 81
 $ : int [1:3] 36 45 80
 $ : int [1:6] 21 41 46 47 80 82
 $ : int [1:5] 31 34 45 56 80
 $ : int [1:2] 29 42
 $ : int [1:3] 44 77 79
 $ : int [1:4] 40 42 43 81
 $ : int [1:3] 39 45 79
 $ : int [1:5] 23 35 45 79 82
 $ : int [1:5] 26 37 39 43 81
 $ : int [1:3] 39 42 44
 $ : int [1:2] 38 43
 $ : int [1:6] 34 36 40 41 79 80
 $ : int [1:5] 8 9 35 47 86
 $ : int [1:5] 8 35 46 80 86
 $ : int [1:5] 50 51 52 53 55
 $ : int [1:4] 28 51 52 54
 $ : int [1:6] 32 48 51 52 54 55
 $ : int [1:4] 48 49 50 52
 $ : int [1:6] 28 48 49 50 51 54
 $ : int [1:2] 48 55
 $ : int [1:5] 24 28 49 50 52
 $ : int [1:4] 48 50 53 75
 $ : int 36
 $ : int [1:5] 1 2 3 58 64
 $ : int [1:5] 2 57 64 66 68
 $ : int [1:3] 60 87 88
 $ : int [1:4] 12 13 59 61
 $ : int [1:5] 12 60 62 63 87
 $ : int [1:4] 61 63 77 87
 $ : int [1:5] 12 18 61 62 83
 $ : int [1:4] 1 57 58 76
 $ : int 76
 $ : int [1:5] 58 67 68 76 84
 $ : int [1:2] 7 66
 $ : int [1:4] 9 58 66 84
 $ : int [1:2] 6 75
 $ : int [1:3] 10 72 73
 $ : int [1:2] 73 74
 $ : int [1:3] 10 11 70
 $ : int [1:4] 19 70 71 74
 $ : int [1:5] 19 21 71 73 86
 $ : int [1:2] 55 69
 $ : int [1:3] 64 65 66
 $ : int [1:3] 23 38 62
 $ : int [1:2] 2 8
 $ : int [1:4] 38 40 41 45
 $ : int [1:5] 34 35 36 45 47
 $ : int [1:5] 25 26 33 39 42
 $ : int [1:6] 19 20 21 23 35 41
 $ : int [1:4] 12 13 16 63
 $ : int [1:4] 7 9 66 68
 $ : int [1:2] 2 5
 $ : int [1:4] 21 46 47 74
 $ : int [1:4] 59 61 62 88
 $ : int [1:2] 59 87
 - attr(*, "class")= chr "nb"
 - attr(*, "region.id")= chr [1:88] "1" "2" "3" "4" ...
 - attr(*, "call")= language dnearneigh(x = coords, d1 = 0, d2 = 62, longlat = TRUE)
 - attr(*, "dnn")= num [1:2] 0 62
 - attr(*, "bounds")= chr [1:2] "GE" "LE"
 - attr(*, "nbtype")= chr "distance"
 - attr(*, "sym")= logi TRUE</code></pre>
</div>
</div>
<p>Another way to display the structure of the weight matrix is to combine&nbsp;<a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/table"><em>table()</em></a>&nbsp;and&nbsp;<a href="https://r-spatial.github.io/spdep/reference/card.html"><em>card()</em></a>&nbsp;of spdep.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(hunan<span class="sc">$</span>County, <span class="fu">card</span>(wm_d62))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
                1 2 3 4 5 6
  Anhua         1 0 0 0 0 0
  Anren         0 0 0 1 0 0
  Anxiang       0 0 0 0 1 0
  Baojing       0 0 0 0 1 0
  Chaling       0 0 1 0 0 0
  Changning     0 0 1 0 0 0
  Changsha      0 0 0 1 0 0
  Chengbu       0 1 0 0 0 0
  Chenxi        0 0 0 1 0 0
  Cili          0 1 0 0 0 0
  Dao           0 0 0 1 0 0
  Dongan        0 0 1 0 0 0
  Dongkou       0 0 0 1 0 0
  Fenghuang     0 0 0 1 0 0
  Guidong       0 0 1 0 0 0
  Guiyang       0 0 0 1 0 0
  Guzhang       0 0 0 0 0 1
  Hanshou       0 0 0 1 0 0
  Hengdong      0 0 0 0 1 0
  Hengnan       0 0 0 0 1 0
  Hengshan      0 0 0 0 0 1
  Hengyang      0 0 0 0 0 1
  Hongjiang     0 0 0 0 1 0
  Huarong       0 0 0 1 0 0
  Huayuan       0 0 0 1 0 0
  Huitong       0 0 0 1 0 0
  Jiahe         0 0 0 0 1 0
  Jianghua      0 0 1 0 0 0
  Jiangyong     0 1 0 0 0 0
  Jingzhou      0 1 0 0 0 0
  Jinshi        0 0 0 1 0 0
  Jishou        0 0 0 0 0 1
  Lanshan       0 0 0 1 0 0
  Leiyang       0 0 0 1 0 0
  Lengshuijiang 0 0 1 0 0 0
  Li            0 0 1 0 0 0
  Lianyuan      0 0 0 0 1 0
  Liling        0 1 0 0 0 0
  Linli         0 0 0 1 0 0
  Linwu         0 0 0 1 0 0
  Linxiang      1 0 0 0 0 0
  Liuyang       0 1 0 0 0 0
  Longhui       0 0 1 0 0 0
  Longshan      0 1 0 0 0 0
  Luxi          0 0 0 0 1 0
  Mayang        0 0 0 0 0 1
  Miluo         0 0 0 0 1 0
  Nan           0 0 0 0 1 0
  Ningxiang     0 0 0 1 0 0
  Ningyuan      0 0 0 0 1 0
  Pingjiang     0 1 0 0 0 0
  Qidong        0 0 1 0 0 0
  Qiyang        0 0 1 0 0 0
  Rucheng       0 1 0 0 0 0
  Sangzhi       0 1 0 0 0 0
  Shaodong      0 0 0 0 1 0
  Shaoshan      0 0 0 0 1 0
  Shaoyang      0 0 0 1 0 0
  Shimen        1 0 0 0 0 0
  Shuangfeng    0 0 0 0 0 1
  Shuangpai     0 0 0 1 0 0
  Suining       0 0 0 0 1 0
  Taojiang      0 1 0 0 0 0
  Taoyuan       0 1 0 0 0 0
  Tongdao       0 1 0 0 0 0
  Wangcheng     0 0 0 1 0 0
  Wugang        0 0 1 0 0 0
  Xiangtan      0 0 0 1 0 0
  Xiangxiang    0 0 0 0 1 0
  Xiangyin      0 0 0 1 0 0
  Xinhua        0 0 0 0 1 0
  Xinhuang      1 0 0 0 0 0
  Xinning       0 1 0 0 0 0
  Xinshao       0 0 0 0 0 1
  Xintian       0 0 0 0 1 0
  Xupu          0 1 0 0 0 0
  Yanling       0 0 1 0 0 0
  Yizhang       1 0 0 0 0 0
  Yongshun      0 0 0 1 0 0
  Yongxing      0 0 0 1 0 0
  You           0 0 0 1 0 0
  Yuanjiang     0 0 0 0 1 0
  Yuanling      1 0 0 0 0 0
  Yueyang       0 0 1 0 0 0
  Zhijiang      0 0 0 0 1 0
  Zhongfang     0 0 0 1 0 0
  Zhuzhou       0 0 0 0 1 0
  Zixing        0 0 1 0 0 0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>n_comp <span class="ot">&lt;-</span> <span class="fu">n.comp.nb</span>(wm_d62)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>n_comp<span class="sc">$</span>nc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(n_comp<span class="sc">$</span>comp.id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1 
88 </code></pre>
</div>
</div>
</section>
<section id="plotting-fixed-distance-weight-matrix" class="level3">
<h3 class="anchored" data-anchor-id="plotting-fixed-distance-weight-matrix">Plotting fixed distance weight matrix</h3>
<p>Next - we will plot the data onto the map.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_d62, coords, <span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k1, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">length=</span><span class="fl">0.08</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="handsonex2_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The red lines show the links of 1st nearest neighbours and the black lines show the links of neighbours within the cut-off distance of 62km.</p>
<p>Alternatively, we can plot both of them next to each other by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"1st nearest neighbours"</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k1, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">length=</span><span class="fl">0.08</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"Distance link"</span>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_d62, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="handsonex2_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="computing-adaptive-distance-weight-matrix" class="level2">
<h2 class="anchored" data-anchor-id="computing-adaptive-distance-weight-matrix">Computing adaptive distance weight matrix</h2>
<p>One of the characteristics of fixed distance weight matrix is that more densely settled areas (usually the urban areas) tend to have more neighbours and the less densely settled areas (usually the rural counties) tend to have lesser neighbours. Having many neighbours smoothes the neighbour relationship across more neighbours.</p>
<p>It is possible to control the numbers of neighbours directly using k-nearest neighbours, either accepting asymmetric neighbours or imposing symmetry as shown in the code chunk below.</p>
<ul>
<li><p><strong><code>knn2nb</code></strong>: This function converts a k-nearest neighbors list to a neighbor list object. It takes the output of the <strong><code>knearneigh</code></strong> function (which calculates k-nearest neighbors) and converts it to a neighbor list suitable for spatial analysis.</p></li>
<li><p><strong><code>knearneigh(coords, k=6)</code></strong>: This function calculates the k-nearest neighbors for a given set of coordinates (<strong><code>coords</code></strong>) with a specified value of <strong><code>k</code></strong> (in this case, <strong><code>k = 6</code></strong>).</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>knn6 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k=</span><span class="dv">6</span>))</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>knn6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 528 
Percentage nonzero weights: 6.818182 
Average number of links: 6 
Non-symmetric neighbours list</code></pre>
</div>
</div>
<p>Similarly, we can display the content of the matrix by using&nbsp;<em>str()</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(knn6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 88
 $ : int [1:6] 2 3 4 5 57 64
 $ : int [1:6] 1 3 57 58 78 85
 $ : int [1:6] 1 2 4 5 57 85
 $ : int [1:6] 1 3 5 6 69 85
 $ : int [1:6] 1 3 4 6 69 85
 $ : int [1:6] 3 4 5 69 75 85
 $ : int [1:6] 9 66 67 71 74 84
 $ : int [1:6] 9 46 47 78 80 86
 $ : int [1:6] 8 46 66 68 84 86
 $ : int [1:6] 16 19 22 70 72 73
 $ : int [1:6] 10 14 16 17 70 72
 $ : int [1:6] 13 15 60 61 63 83
 $ : int [1:6] 12 15 60 61 63 83
 $ : int [1:6] 11 15 16 17 72 83
 $ : int [1:6] 12 13 14 17 60 83
 $ : int [1:6] 10 11 17 22 72 83
 $ : int [1:6] 10 11 14 16 72 83
 $ : int [1:6] 20 22 23 63 77 83
 $ : int [1:6] 10 20 21 73 74 82
 $ : int [1:6] 18 19 21 22 23 82
 $ : int [1:6] 19 20 35 74 82 86
 $ : int [1:6] 10 16 18 19 20 83
 $ : int [1:6] 18 20 41 77 79 82
 $ : int [1:6] 25 28 31 52 54 81
 $ : int [1:6] 24 28 31 33 54 81
 $ : int [1:6] 25 27 29 33 42 81
 $ : int [1:6] 26 29 30 37 42 81
 $ : int [1:6] 24 25 33 49 52 54
 $ : int [1:6] 26 27 37 42 43 81
 $ : int [1:6] 26 27 28 33 49 81
 $ : int [1:6] 24 25 36 39 40 54
 $ : int [1:6] 24 31 50 54 55 56
 $ : int [1:6] 25 26 28 30 49 81
 $ : int [1:6] 36 40 41 45 56 80
 $ : int [1:6] 21 41 46 47 80 82
 $ : int [1:6] 31 34 40 45 56 80
 $ : int [1:6] 26 27 29 42 43 44
 $ : int [1:6] 23 43 44 62 77 79
 $ : int [1:6] 25 40 42 43 44 81
 $ : int [1:6] 31 36 39 43 45 79
 $ : int [1:6] 23 35 45 79 80 82
 $ : int [1:6] 26 27 37 39 43 81
 $ : int [1:6] 37 39 40 42 44 79
 $ : int [1:6] 37 38 39 42 43 79
 $ : int [1:6] 34 36 40 41 79 80
 $ : int [1:6] 8 9 35 47 78 86
 $ : int [1:6] 8 21 35 46 80 86
 $ : int [1:6] 49 50 51 52 53 55
 $ : int [1:6] 28 33 48 51 52 54
 $ : int [1:6] 32 48 51 52 54 55
 $ : int [1:6] 28 48 49 50 52 54
 $ : int [1:6] 28 48 49 50 51 54
 $ : int [1:6] 48 50 51 52 55 75
 $ : int [1:6] 24 28 49 50 51 52
 $ : int [1:6] 32 48 50 52 53 75
 $ : int [1:6] 32 34 36 78 80 85
 $ : int [1:6] 1 2 3 58 64 68
 $ : int [1:6] 2 57 64 66 68 78
 $ : int [1:6] 12 13 60 61 87 88
 $ : int [1:6] 12 13 59 61 63 87
 $ : int [1:6] 12 13 60 62 63 87
 $ : int [1:6] 12 38 61 63 77 87
 $ : int [1:6] 12 18 60 61 62 83
 $ : int [1:6] 1 3 57 58 68 76
 $ : int [1:6] 58 64 66 67 68 76
 $ : int [1:6] 9 58 67 68 76 84
 $ : int [1:6] 7 65 66 68 76 84
 $ : int [1:6] 9 57 58 66 78 84
 $ : int [1:6] 4 5 6 32 75 85
 $ : int [1:6] 10 16 19 22 72 73
 $ : int [1:6] 7 19 73 74 84 86
 $ : int [1:6] 10 11 14 16 17 70
 $ : int [1:6] 10 19 21 70 71 74
 $ : int [1:6] 19 21 71 73 84 86
 $ : int [1:6] 6 32 50 53 55 69
 $ : int [1:6] 58 64 65 66 67 68
 $ : int [1:6] 18 23 38 61 62 63
 $ : int [1:6] 2 8 9 46 58 68
 $ : int [1:6] 38 40 41 43 44 45
 $ : int [1:6] 34 35 36 41 45 47
 $ : int [1:6] 25 26 28 33 39 42
 $ : int [1:6] 19 20 21 23 35 41
 $ : int [1:6] 12 13 15 16 22 63
 $ : int [1:6] 7 9 66 68 71 74
 $ : int [1:6] 2 3 4 5 56 69
 $ : int [1:6] 8 9 21 46 47 74
 $ : int [1:6] 59 60 61 62 63 88
 $ : int [1:6] 59 60 61 62 63 87
 - attr(*, "region.id")= chr [1:88] "1" "2" "3" "4" ...
 - attr(*, "call")= language knearneigh(x = coords, k = 6)
 - attr(*, "sym")= logi FALSE
 - attr(*, "type")= chr "knn"
 - attr(*, "knn-k")= num 6
 - attr(*, "class")= chr "nb"</code></pre>
</div>
</div>
<section id="plotting-distance-based-neighbours" class="level3">
<h3 class="anchored" data-anchor-id="plotting-distance-based-neighbours">Plotting distance based neighbours</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hunan<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(knn6, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="handsonex2_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="weights-based-on-inverse-distance-weighting" class="level2">
<h2 class="anchored" data-anchor-id="weights-based-on-inverse-distance-weighting">Weights based on Inverse Distance Weighting</h2>
<p>The IDW method estimates values for unmeasured locations based on the values observed at nearby locations. The basic idea is that values at a particular location are influenced more by values at nearby locations than by those farther away.</p>
<p>Here’s a brief explanation of how IDW works:</p>
<ol type="1">
<li><p><strong>Inverse Distance Weighting:</strong></p>
<ul>
<li><p>IDW assigns weights to measured values at known locations based on their distance to the location where you want to estimate a value.</p></li>
<li><p>The weights are typically inversely proportional to the distance from the known points. Closer points have higher weights, indicating a stronger influence on the estimated value.</p></li>
</ul></li>
<li><p><strong>Weighted Average:</strong></p>
<ul>
<li>The estimated value at a specific location is calculated as a weighted average of the observed values at nearby locations, with weights determined by their inverse distances.</li>
</ul></li>
<li><p><strong>Power Parameter:</strong></p>
<ul>
<li>IDW often includes a power parameter (p) that allows you to control the rate at which the weights decrease with distance. A higher value of p means that closer points have even more influence on the estimated value.</li>
</ul></li>
</ol>
<p>First, we will compute the distances between areas by using&nbsp;<a href="https://r-spatial.github.io/spdep/reference/nbdists.html"><em>nbdists()</em></a>&nbsp;of&nbsp;<strong>spdep</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> <span class="fu">nbdists</span>(wm_q, coords, <span class="at">longlat =</span> <span class="cn">TRUE</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>ids <span class="ot">&lt;-</span> <span class="fu">lapply</span>(dist, <span class="cf">function</span>(x) <span class="dv">1</span><span class="sc">/</span>(x))</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>ids</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.01535405 0.03916350 0.01820896 0.02807922 0.01145113

[[2]]
[1] 0.01535405 0.01764308 0.01925924 0.02323898 0.01719350

[[3]]
[1] 0.03916350 0.02822040 0.03695795 0.01395765

[[4]]
[1] 0.01820896 0.02822040 0.03414741 0.01539065

[[5]]
[1] 0.03695795 0.03414741 0.01524598 0.01618354

[[6]]
[1] 0.015390649 0.015245977 0.021748129 0.011883901 0.009810297

[[7]]
[1] 0.01708612 0.01473997 0.01150924 0.01872915

[[8]]
[1] 0.02022144 0.03453056 0.02529256 0.01036340 0.02284457 0.01500600 0.01515314

[[9]]
[1] 0.02022144 0.01574888 0.02109502 0.01508028 0.02902705 0.01502980

[[10]]
[1] 0.02281552 0.01387777 0.01538326 0.01346650 0.02100510 0.02631658 0.01874863
[8] 0.01500046

[[11]]
[1] 0.01882869 0.02243492 0.02247473

[[12]]
[1] 0.02779227 0.02419652 0.02333385 0.02986130 0.02335429

[[13]]
[1] 0.02779227 0.02650020 0.02670323 0.01714243

[[14]]
[1] 0.01882869 0.01233868 0.02098555

[[15]]
[1] 0.02650020 0.01233868 0.01096284 0.01562226

[[16]]
[1] 0.02281552 0.02466962 0.02765018 0.01476814 0.01671430

[[17]]
[1] 0.01387777 0.02243492 0.02098555 0.01096284 0.02466962 0.01593341 0.01437996

[[18]]
[1] 0.02039779 0.02032767 0.01481665 0.01473691 0.01459380

[[19]]
[1] 0.01538326 0.01926323 0.02668415 0.02140253 0.01613589 0.01412874

[[20]]
[1] 0.01346650 0.02039779 0.01926323 0.01723025 0.02153130 0.01469240 0.02327034

[[21]]
[1] 0.02668415 0.01723025 0.01766299 0.02644986 0.02163800

[[22]]
[1] 0.02100510 0.02765018 0.02032767 0.02153130 0.01489296

[[23]]
[1] 0.01481665 0.01469240 0.01401432 0.02246233 0.01880425 0.01530458 0.01849605

[[24]]
[1] 0.02354598 0.01837201 0.02607264 0.01220154 0.02514180

[[25]]
[1] 0.02354598 0.02188032 0.01577283 0.01949232 0.02947957

[[26]]
[1] 0.02155798 0.01745522 0.02212108 0.02220532

[[27]]
[1] 0.02155798 0.02490625 0.01562326

[[28]]
[1] 0.01837201 0.02188032 0.02229549 0.03076171 0.02039506

[[29]]
[1] 0.02490625 0.01686587 0.01395022

[[30]]
[1] 0.02090587

[[31]]
[1] 0.02607264 0.01577283 0.01219005 0.01724850 0.01229012 0.01609781 0.01139438
[8] 0.01150130

[[32]]
[1] 0.01220154 0.01219005 0.01712515 0.01340413 0.01280928 0.01198216 0.01053374
[8] 0.01065655

[[33]]
[1] 0.01949232 0.01745522 0.02229549 0.02090587 0.01979045

[[34]]
[1] 0.03113041 0.03589551 0.02882915

[[35]]
[1] 0.01766299 0.02185795 0.02616766 0.02111721 0.02108253 0.01509020

[[36]]
[1] 0.01724850 0.03113041 0.01571707 0.01860991 0.02073549 0.01680129

[[37]]
[1] 0.01686587 0.02234793 0.01510990 0.01550676

[[38]]
[1] 0.01401432 0.02407426 0.02276151 0.01719415

[[39]]
[1] 0.01229012 0.02172543 0.01711924 0.02629732 0.01896385

[[40]]
[1] 0.01609781 0.01571707 0.02172543 0.01506473 0.01987922 0.01894207

[[41]]
[1] 0.02246233 0.02185795 0.02205991 0.01912542 0.01601083 0.01742892

[[42]]
[1] 0.02212108 0.01562326 0.01395022 0.02234793 0.01711924 0.01836831 0.01683518

[[43]]
[1] 0.01510990 0.02629732 0.01506473 0.01836831 0.03112027 0.01530782

[[44]]
[1] 0.01550676 0.02407426 0.03112027 0.01486508

[[45]]
[1] 0.03589551 0.01860991 0.01987922 0.02205991 0.02107101 0.01982700

[[46]]
[1] 0.03453056 0.04033752 0.02689769

[[47]]
[1] 0.02529256 0.02616766 0.04033752 0.01949145 0.02181458

[[48]]
[1] 0.02313819 0.03370576 0.02289485 0.01630057 0.01818085

[[49]]
[1] 0.03076171 0.02138091 0.02394529 0.01990000

[[50]]
[1] 0.01712515 0.02313819 0.02551427 0.02051530 0.02187179

[[51]]
[1] 0.03370576 0.02138091 0.02873854

[[52]]
[1] 0.02289485 0.02394529 0.02551427 0.02873854 0.03516672

[[53]]
[1] 0.01630057 0.01979945 0.01253977

[[54]]
[1] 0.02514180 0.02039506 0.01340413 0.01990000 0.02051530 0.03516672

[[55]]
[1] 0.01280928 0.01818085 0.02187179 0.01979945 0.01882298

[[56]]
[1] 0.01036340 0.01139438 0.01198216 0.02073549 0.01214479 0.01362855 0.01341697

[[57]]
[1] 0.028079221 0.017643082 0.031423501 0.029114131 0.013520292 0.009903702

[[58]]
[1] 0.01925924 0.03142350 0.02722997 0.01434859 0.01567192

[[59]]
[1] 0.01696711 0.01265572 0.01667105 0.01785036

[[60]]
[1] 0.02419652 0.02670323 0.01696711 0.02343040

[[61]]
[1] 0.02333385 0.01265572 0.02343040 0.02514093 0.02790764 0.01219751 0.02362452

[[62]]
[1] 0.02514093 0.02002219 0.02110260

[[63]]
[1] 0.02986130 0.02790764 0.01407043 0.01805987

[[64]]
[1] 0.02911413 0.01689892

[[65]]
[1] 0.02471705

[[66]]
[1] 0.01574888 0.01726461 0.03068853 0.01954805 0.01810569

[[67]]
[1] 0.01708612 0.01726461 0.01349843 0.01361172

[[68]]
[1] 0.02109502 0.02722997 0.03068853 0.01406357 0.01546511

[[69]]
[1] 0.02174813 0.01645838 0.01419926

[[70]]
[1] 0.02631658 0.01963168 0.02278487

[[71]]
[1] 0.01473997 0.01838483 0.03197403

[[72]]
[1] 0.01874863 0.02247473 0.01476814 0.01593341 0.01963168

[[73]]
[1] 0.01500046 0.02140253 0.02278487 0.01838483 0.01652709

[[74]]
[1] 0.01150924 0.01613589 0.03197403 0.01652709 0.01342099 0.02864567

[[75]]
[1] 0.011883901 0.010533736 0.012539774 0.018822977 0.016458383 0.008217581

[[76]]
[1] 0.01352029 0.01434859 0.01689892 0.02471705 0.01954805 0.01349843 0.01406357

[[77]]
[1] 0.014736909 0.018804247 0.022761507 0.012197506 0.020022195 0.014070428
[7] 0.008440896

[[78]]
[1] 0.02323898 0.02284457 0.01508028 0.01214479 0.01567192 0.01546511 0.01140779

[[79]]
[1] 0.01530458 0.01719415 0.01894207 0.01912542 0.01530782 0.01486508 0.02107101

[[80]]
[1] 0.01500600 0.02882915 0.02111721 0.01680129 0.01601083 0.01982700 0.01949145
[8] 0.01362855

[[81]]
[1] 0.02947957 0.02220532 0.01150130 0.01979045 0.01896385 0.01683518

[[82]]
[1] 0.02327034 0.02644986 0.01849605 0.02108253 0.01742892

[[83]]
[1] 0.023354289 0.017142433 0.015622258 0.016714303 0.014379961 0.014593799
[7] 0.014892965 0.018059871 0.008440896

[[84]]
[1] 0.01872915 0.02902705 0.01810569 0.01361172 0.01342099 0.01297994

[[85]]
 [1] 0.011451133 0.017193502 0.013957649 0.016183544 0.009810297 0.010656545
 [7] 0.013416965 0.009903702 0.014199260 0.008217581 0.011407794

[[86]]
[1] 0.01515314 0.01502980 0.01412874 0.02163800 0.01509020 0.02689769 0.02181458
[8] 0.02864567 0.01297994

[[87]]
[1] 0.01667105 0.02362452 0.02110260 0.02058034

[[88]]
[1] 0.01785036 0.02058034</code></pre>
</div>
</div>
<section id="row-standardised-weights-matrix" class="level3">
<h3 class="anchored" data-anchor-id="row-standardised-weights-matrix">Row-standardised weights matrix</h3>
<p>Next, we need to assign weights to each neighboring polygon. In our case, each neighboring polygon will be assigned equal weight (style="W"). This is accomplished by assigning the fraction 1/(#ofneighbors) to each neighboring county then summing the weighted income values. While this is the most intuitive way to summaries the neighbors' values it has one drawback in that polygons along the edges of the study area will base their lagged values on fewer polygons thus potentially over- or under-estimating the true nature of the spatial autocorrelation in the data. For this example, we'll stick with the style="W" option for simplicity's sake but note that other more robust options are available, notably style="B".</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>rswm_q <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_q, <span class="at">style=</span><span class="st">"W"</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>rswm_q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 88 
Number of nonzero links: 448 
Percentage nonzero weights: 5.785124 
Average number of links: 5.090909 

Weights style: W 
Weights constants summary:
   n   nn S0       S1       S2
W 88 7744 88 37.86334 365.9147</code></pre>
</div>
</div>
<p>The zero.policy=TRUE option allows for lists of non-neighbors. This should be used with caution since the user may not be aware of missing neighbors in their dataset however, a zero.policy of FALSE would return an error.</p>
<p>To see the weight of the first polygon's eight neighbors type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>rswm_q<span class="sc">$</span>weights[<span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125</code></pre>
</div>
</div>
<p>Each neighbor is assigned a 0.125 of the total weight. This means that when R computes the average neighboring income values, each neighbor's income will be multiplied by 0.2 before being tallied.</p>
<p>Using the same method, we can also derive a row standardised distance weight matrix by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>rswm_ids <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_q, <span class="at">glist=</span>ids, <span class="at">style=</span><span class="st">"B"</span>, <span class="at">zero.policy=</span><span class="cn">TRUE</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>rswm_ids</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 88 
Number of nonzero links: 448 
Percentage nonzero weights: 5.785124 
Average number of links: 5.090909 

Weights style: B 
Weights constants summary:
   n   nn       S0        S1     S2
B 88 7744 8.786867 0.3776535 3.8137</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>rswm_ids<span class="sc">$</span>weights[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.01535405 0.03916350 0.01820896 0.02807922 0.01145113</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">unlist</span>(rswm_ids<span class="sc">$</span>weights))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
0.008218 0.015088 0.018739 0.019614 0.022823 0.040338 </code></pre>
</div>
</div>
</section>
</section>
<section id="application-of-spatial-weight-matrix" class="level2">
<h2 class="anchored" data-anchor-id="application-of-spatial-weight-matrix">Application of Spatial Weight Matrix</h2>
<ol type="1">
<li><p><strong>Spatial Lag with Row-Standardized Weights:</strong></p>
<ul>
<li><p>This involves creating a new variable for each observation that represents the average or weighted average of the variable of interest in its neighboring locations.</p></li>
<li><p>The weights used for the spatial lag are row-standardized weights, meaning that each row of the spatial weights matrix sums to 1.</p></li>
</ul></li>
<li><p><strong>Spatial Lag as a Sum of Neighboring Values:</strong></p>
<ul>
<li><p>Instead of using row-standardized weights, this approach calculates the spatial lag as the sum of the values of the variable of interest in neighboring locations.</p></li>
<li><p>This is a simple summation of the neighboring values without normalization.</p></li>
</ul></li>
<li><p><strong>Spatial Window Average:</strong></p>
<ul>
<li><p>This involves creating a new variable for each observation that represents the average value of the variable of interest within a specified spatial window or neighborhood around that observation.</p></li>
<li><p>The window can be defined by distance, number of neighbors, or some other criterion.</p></li>
</ul></li>
<li><p><strong>Spatial Window Sum:</strong></p>
<ul>
<li>Similar to the spatial window average, this creates a new variable that represents the sum of the variable of interest within a specified spatial window or neighborhood around each observation.</li>
</ul></li>
</ol>
<p>The choice of which spatial lag variable to use depends on the specific research question, the characteristics of your data, and the underlying assumptions of your analysis. Here’s a general guide on when to use each of the four spatial lag variables you mentioned:</p>
<ol type="1">
<li><strong>Spatial Lag with Row-Standardized Weights:</strong>
<ul>
<li><strong>Use Case:</strong> This is a commonly used spatial lag variable when you want to account for spatial autocorrelation and consider the average or weighted average of a variable in neighboring locations.</li>
<li><strong>Considerations:</strong> Useful when you want each observation’s influence to be normalized by its connectivity to neighbors. It is often used in spatial econometrics.</li>
</ul></li>
<li><strong>Spatial Lag as a Sum of Neighboring Values:</strong>
<ul>
<li><strong>Use Case:</strong> When you are interested in capturing the cumulative impact of neighboring values on a variable, without normalizing by the number of neighbors.</li>
<li><strong>Considerations:</strong> May be appropriate when you want to emphasize the total influence of neighbors, regardless of the number of neighbors.</li>
</ul></li>
<li><strong>Spatial Window Average:</strong>
<ul>
<li><strong>Use Case:</strong> Useful when you want to smooth the variable by considering the average value within a specified spatial window or neighborhood around each observation.</li>
<li><strong>Considerations:</strong> Good for capturing a local spatial pattern while reducing noise. The size of the window affects the level of smoothing.</li>
</ul></li>
<li><strong>Spatial Window Sum:</strong>
<ul>
<li><strong>Use Case:</strong> When you want to emphasize the cumulative impact of the variable within a specified spatial window or neighborhood.</li>
<li><strong>Considerations:</strong> Similar to the spatial window average, but places more weight on higher values within the window. Useful when you want to capture intensity or density rather than an average.</li>
</ul></li>
</ol>
<p>Consider the following factors when choosing which spatial lag variable to use:</p>
<ul>
<li><p><strong>Spatial Patterns:</strong> Consider the spatial patterns in your data. Are you interested in capturing local averages, totals, or smoothing effects?</p></li>
<li><p><strong>Assumptions:</strong> Think about the assumptions underlying each approach. For example, row-standardized weights normalize the influence of neighbors, while a simple sum does not.</p></li>
<li><p><strong>Interpretability:</strong> Choose the variable that aligns with the interpretability of your research question. What type of spatial influence are you trying to capture?</p></li>
<li><p><strong>Modeling Goals:</strong> If you’re incorporating these spatial lag variables into a regression model, consider the assumptions and requirements of the modeling technique you are using.</p></li>
</ul>
<p>Experimenting with different spatial lag variables and assessing their impact on your analysis can also provide insights into which approach is most appropriate for your specific context.</p>
<section id="spatial-lag-with-row-standardised-weights" class="level3">
<h3 class="anchored" data-anchor-id="spatial-lag-with-row-standardised-weights">Spatial lag with row-standardised weights</h3>
<p>Finally, we'll compute the average neighbor GDPPC value for each polygon. These values are often referred to as&nbsp;<strong>spatially lagged values</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>GDPPC.lag <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(rswm_q, hunan<span class="sc">$</span>GDPPC)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>GDPPC.lag</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 24847.20 22724.80 24143.25 27737.50 27270.25 21248.80 43747.00 33582.71
 [9] 45651.17 32027.62 32671.00 20810.00 25711.50 30672.33 33457.75 31689.20
[17] 20269.00 23901.60 25126.17 21903.43 22718.60 25918.80 20307.00 20023.80
[25] 16576.80 18667.00 14394.67 19848.80 15516.33 20518.00 17572.00 15200.12
[33] 18413.80 14419.33 24094.50 22019.83 12923.50 14756.00 13869.80 12296.67
[41] 15775.17 14382.86 11566.33 13199.50 23412.00 39541.00 36186.60 16559.60
[49] 20772.50 19471.20 19827.33 15466.80 12925.67 18577.17 14943.00 24913.00
[57] 25093.00 24428.80 17003.00 21143.75 20435.00 17131.33 24569.75 23835.50
[65] 26360.00 47383.40 55157.75 37058.00 21546.67 23348.67 42323.67 28938.60
[73] 25880.80 47345.67 18711.33 29087.29 20748.29 35933.71 15439.71 29787.50
[81] 18145.00 21617.00 29203.89 41363.67 22259.09 44939.56 16902.00 16930.00</code></pre>
</div>
</div>
<p>We utilised the rswm_q here.</p>
<p>Recalled in the previous section, we retrieved the GDPPC of these five countries by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>nb1 <span class="ot">&lt;-</span> wm_q[[<span class="dv">1</span>]]</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>nb1 <span class="ot">&lt;-</span> hunan<span class="sc">$</span>GDPPC[nb1]</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>nb1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20981 34592 24473 21311 22879</code></pre>
</div>
</div>
<p>Question: Can you see the meaning of Spatial lag with row-standardized weights now? - We are summarising the values of hte variable in the neighbouring locations in a way that fives equal importance to each neighbour and ensured that the influence of neghbours is normalised.</p>
<p>We can append the spatially lag GDPPC values onto hunan sf data frame by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>lag.list <span class="ot">&lt;-</span> <span class="fu">list</span>(hunan<span class="sc">$</span>NAME_3, <span class="fu">lag.listw</span>(rswm_q, hunan<span class="sc">$</span>GDPPC))</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>lag.res <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(lag.list)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(lag.res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"NAME_3"</span>, <span class="st">"lag GDPPC"</span>)</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>hunan <span class="ot">&lt;-</span> <span class="fu">left_join</span>(hunan,lag.res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The following table shows the average neighboring income values (stored in the Inc.lag object) for each county.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hunan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 7 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 110.4922 ymin: 28.61762 xmax: 112.3013 ymax: 30.12812
Geodetic CRS:  WGS 84
   NAME_2  ID_3  NAME_3   ENGTYPE_3  County GDPPC lag GDPPC
1 Changde 21098 Anxiang      County Anxiang 23667  24847.20
2 Changde 21100 Hanshou      County Hanshou 20981  22724.80
3 Changde 21101  Jinshi County City  Jinshi 34592  24143.25
4 Changde 21102      Li      County      Li 24473  27737.50
5 Changde 21103   Linli      County   Linli 25554  27270.25
6 Changde 21104  Shimen      County  Shimen 27137  21248.80
                        geometry
1 POLYGON ((112.0625 29.75523...
2 POLYGON ((112.2288 29.11684...
3 POLYGON ((111.8927 29.6013,...
4 POLYGON ((111.3731 29.94649...
5 POLYGON ((111.6324 29.76288...
6 POLYGON ((110.8825 30.11675...</code></pre>
</div>
</div>
<p>Next, we will plot both the GDPPC and spatial lag GDPPC for comparison using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"GDPPC"</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>lag_gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"lag GDPPC"</span>)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(gdppc, lag_gdppc, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="handsonex2_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="spatial-lag-as-a-sum-of-neighbouring-values" class="level3">
<h3 class="anchored" data-anchor-id="spatial-lag-as-a-sum-of-neighbouring-values">Spatial lag as a sum of neighbouring values</h3>
<p>We can calculate spatial lag as a sum of neighboring values by assigning binary weights. This requires us to go back to our neighbors list, then apply a function that will assign binary weights, then we use glist = in the nb2listw function to explicitly assign these weights.</p>
<p>We start by applying a function that will assign a value of 1 per each neighbor. This is done with lapply, which we have been using to manipulate the neighbors structure throughout the past notebooks. Basically it applies a function across each value in the neighbors structure.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>b_weights <span class="ot">&lt;-</span> <span class="fu">lapply</span>(wm_q, <span class="cf">function</span>(x) <span class="dv">0</span><span class="sc">*</span>x <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>b_weights2 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_q, </span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">glist =</span> b_weights, </span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">style =</span> <span class="st">"B"</span>)</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>b_weights2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 88 
Number of nonzero links: 448 
Percentage nonzero weights: 5.785124 
Average number of links: 5.090909 

Weights style: B 
Weights constants summary:
   n   nn  S0  S1    S2
B 88 7744 448 896 10224</code></pre>
</div>
</div>
<p>With the proper weights assigned, we can use lag.listw to compute a lag variable from our weight and GDPPC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>lag_sum <span class="ot">&lt;-</span> <span class="fu">list</span>(hunan<span class="sc">$</span>NAME_3, <span class="fu">lag.listw</span>(b_weights2, hunan<span class="sc">$</span>GDPPC))</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>lag.res <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(lag_sum)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(lag.res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"NAME_3"</span>, <span class="st">"lag_sum GDPPC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Examine the result.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>lag_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
 [1] "Anxiang"       "Hanshou"       "Jinshi"        "Li"           
 [5] "Linli"         "Shimen"        "Liuyang"       "Ningxiang"    
 [9] "Wangcheng"     "Anren"         "Guidong"       "Jiahe"        
[13] "Linwu"         "Rucheng"       "Yizhang"       "Yongxing"     
[17] "Zixing"        "Changning"     "Hengdong"      "Hengnan"      
[21] "Hengshan"      "Leiyang"       "Qidong"        "Chenxi"       
[25] "Zhongfang"     "Huitong"       "Jingzhou"      "Mayang"       
[29] "Tongdao"       "Xinhuang"      "Xupu"          "Yuanling"     
[33] "Zhijiang"      "Lengshuijiang" "Shuangfeng"    "Xinhua"       
[37] "Chengbu"       "Dongan"        "Dongkou"       "Longhui"      
[41] "Shaodong"      "Suining"       "Wugang"        "Xinning"      
[45] "Xinshao"       "Shaoshan"      "Xiangxiang"    "Baojing"      
[49] "Fenghuang"     "Guzhang"       "Huayuan"       "Jishou"       
[53] "Longshan"      "Luxi"          "Yongshun"      "Anhua"        
[57] "Nan"           "Yuanjiang"     "Jianghua"      "Lanshan"      
[61] "Ningyuan"      "Shuangpai"     "Xintian"       "Huarong"      
[65] "Linxiang"      "Miluo"         "Pingjiang"     "Xiangyin"     
[69] "Cili"          "Chaling"       "Liling"        "Yanling"      
[73] "You"           "Zhuzhou"       "Sangzhi"       "Yueyang"      
[77] "Qiyang"        "Taojiang"      "Shaoyang"      "Lianyuan"     
[81] "Hongjiang"     "Hengyang"      "Guiyang"       "Changsha"     
[85] "Taoyuan"       "Xiangtan"      "Dao"           "Jiangyong"    

[[2]]
 [1] 124236 113624  96573 110950 109081 106244 174988 235079 273907 256221
[11]  98013 104050 102846  92017 133831 158446 141883 119508 150757 153324
[21] 113593 129594 142149 100119  82884  74668  43184  99244  46549  20518
[31] 140576 121601  92069  43258 144567 132119  51694  59024  69349  73780
[41]  94651 100680  69398  52798 140472 118623 180933  82798  83090  97356
[51]  59482  77334  38777 111463  74715 174391 150558 122144  68012  84575
[61] 143045  51394  98279  47671  26360 236917 220631 185290  64640  70046
[71] 126971 144693 129404 284074 112268 203611 145238 251536 108078 238300
[81] 108870 108085 262835 248182 244850 404456  67608  33860</code></pre>
</div>
</div>
<p>Question: Can you understand the meaning of Spatial lag as a sum of neighboring values now? a simple summation of the neighbouring values without normalisation.</p>
<p>Next, we will append the&nbsp;<em>lag_sum GDPPC</em>&nbsp;field into&nbsp;<code>hunan</code>&nbsp;sf data frame by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>hunan <span class="ot">&lt;-</span> <span class="fu">left_join</span>(hunan, lag.res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, We can plot both the&nbsp;<em>GDPPC</em>&nbsp;and&nbsp;<em>Spatial Lag Sum GDPPC</em>&nbsp;for comparison using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"GDPPC"</span>)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>lag_sum_gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"lag_sum GDPPC"</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(gdppc, lag_sum_gdppc, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="handsonex2_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="spatial-window-average" class="level3">
<h3 class="anchored" data-anchor-id="spatial-window-average">Spatial window average</h3>
<p>The spatial window average uses row-standardized weights and includes the diagonal element. To do this in R, we need to go back to the neighbors structure and add the diagonal element before assigning weights.</p>
<p>To add the diagonal element to the neighbour list, we just need to use <em>include.self()</em> from <strong>spdep</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>wm_qs <span class="ot">&lt;-</span> <span class="fu">include.self</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Notice that the Number of nonzero links, Percentage nonzero weights and Average number of links are 536, 6.921488 and 6.090909 respectively as compared to wm_q of 448, 5.785124 and 5.090909</p>
<p>Let us take a good look at the neighbour list of area [1] by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>wm_qs[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  1  2  3  4 57 85</code></pre>
</div>
</div>
<p>Notice that now [1] has six neighbours instead of five.</p>
<p>Now we obtain weights with <em>nb2listw()</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>wm_qs <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_qs)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>wm_qs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 88 
Number of nonzero links: 536 
Percentage nonzero weights: 6.921488 
Average number of links: 6.090909 

Weights style: W 
Weights constants summary:
   n   nn S0       S1       S2
W 88 7744 88 30.90265 357.5308</code></pre>
</div>
</div>
<p>Again, we use <em>nb2listw()</em> and <em>glist()</em> to explicitly assign weight values.</p>
<p>Lastly, we just need to create the lag variable from our weight structure and GDPPC variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>lag_w_avg_gpdpc <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(wm_qs, </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>                             hunan<span class="sc">$</span>GDPPC)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>lag_w_avg_gpdpc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 24650.50 22434.17 26233.00 27084.60 26927.00 22230.17 47621.20 37160.12
 [9] 49224.71 29886.89 26627.50 22690.17 25366.40 25825.75 30329.00 32682.83
[17] 25948.62 23987.67 25463.14 21904.38 23127.50 25949.83 20018.75 19524.17
[25] 18955.00 17800.40 15883.00 18831.33 14832.50 17965.00 17159.89 16199.44
[33] 18764.50 26878.75 23188.86 20788.14 12365.20 15985.00 13764.83 11907.43
[41] 17128.14 14593.62 11644.29 12706.00 21712.29 43548.25 35049.00 16226.83
[49] 19294.40 18156.00 19954.75 18145.17 12132.75 18419.29 14050.83 23619.75
[57] 24552.71 24733.67 16762.60 20932.60 19467.75 18334.00 22541.00 26028.00
[65] 29128.50 46569.00 47576.60 36545.50 20838.50 22531.00 42115.50 27619.00
[73] 27611.33 44523.29 18127.43 28746.38 20734.50 33880.62 14716.38 28516.22
[81] 18086.14 21244.50 29568.80 48119.71 22310.75 43151.60 17133.40 17009.33</code></pre>
</div>
</div>
<p>Next, we will convert the lag variable listw object into a data.frame by using&nbsp;<em>as.data.frame()</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>lag.list.wm_qs <span class="ot">&lt;-</span> <span class="fu">list</span>(hunan<span class="sc">$</span>NAME_3, <span class="fu">lag.listw</span>(wm_qs, hunan<span class="sc">$</span>GDPPC))</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>lag_wm_qs.res <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(lag.list.wm_qs)</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(lag_wm_qs.res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"NAME_3"</span>, <span class="st">"lag_window_avg GDPPC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note: The third command line on the code chunk above renames the field names of <em>lag_wm_q1.res</em> object into <em>NAME_3</em> and <em>lag_window_avg GDPPC</em> respectively.</p>
<p>Next, the code chunk below will be used to append <em>lag_window_avg GDPPC</em> values onto <em>hunan</em> sf data.frame by using <em>left_join()</em> of <strong>dplyr</strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>hunan <span class="ot">&lt;-</span> <span class="fu">left_join</span>(hunan, lag_wm_qs.res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To compare the values of lag GDPPC and Spatial window average,&nbsp;<code>kable()</code>&nbsp;of Knitr package is used to prepare a table using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>hunan <span class="sc">%&gt;%</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"County"</span>, </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>         <span class="st">"lag GDPPC"</span>, </span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>         <span class="st">"lag_window_avg GDPPC"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 27%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">lag GDPPC</th>
<th style="text-align: right;">lag_window_avg GDPPC</th>
<th style="text-align: left;">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anxiang</td>
<td style="text-align: right;">24847.20</td>
<td style="text-align: right;">24650.50</td>
<td style="text-align: left;">POLYGON ((112.0625 29.75523…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hanshou</td>
<td style="text-align: right;">22724.80</td>
<td style="text-align: right;">22434.17</td>
<td style="text-align: left;">POLYGON ((112.2288 29.11684…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jinshi</td>
<td style="text-align: right;">24143.25</td>
<td style="text-align: right;">26233.00</td>
<td style="text-align: left;">POLYGON ((111.8927 29.6013,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Li</td>
<td style="text-align: right;">27737.50</td>
<td style="text-align: right;">27084.60</td>
<td style="text-align: left;">POLYGON ((111.3731 29.94649…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linli</td>
<td style="text-align: right;">27270.25</td>
<td style="text-align: right;">26927.00</td>
<td style="text-align: left;">POLYGON ((111.6324 29.76288…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shimen</td>
<td style="text-align: right;">21248.80</td>
<td style="text-align: right;">22230.17</td>
<td style="text-align: left;">POLYGON ((110.8825 30.11675…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Liuyang</td>
<td style="text-align: right;">43747.00</td>
<td style="text-align: right;">47621.20</td>
<td style="text-align: left;">POLYGON ((113.9905 28.5682,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ningxiang</td>
<td style="text-align: right;">33582.71</td>
<td style="text-align: right;">37160.12</td>
<td style="text-align: left;">POLYGON ((112.7181 28.38299…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wangcheng</td>
<td style="text-align: right;">45651.17</td>
<td style="text-align: right;">49224.71</td>
<td style="text-align: left;">POLYGON ((112.7914 28.52688…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anren</td>
<td style="text-align: right;">32027.62</td>
<td style="text-align: right;">29886.89</td>
<td style="text-align: left;">POLYGON ((113.1757 26.82734…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guidong</td>
<td style="text-align: right;">32671.00</td>
<td style="text-align: right;">26627.50</td>
<td style="text-align: left;">POLYGON ((114.1799 26.20117…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jiahe</td>
<td style="text-align: right;">20810.00</td>
<td style="text-align: right;">22690.17</td>
<td style="text-align: left;">POLYGON ((112.4425 25.74358…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linwu</td>
<td style="text-align: right;">25711.50</td>
<td style="text-align: right;">25366.40</td>
<td style="text-align: left;">POLYGON ((112.5914 25.55143…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rucheng</td>
<td style="text-align: right;">30672.33</td>
<td style="text-align: right;">25825.75</td>
<td style="text-align: left;">POLYGON ((113.6759 25.87578…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yizhang</td>
<td style="text-align: right;">33457.75</td>
<td style="text-align: right;">30329.00</td>
<td style="text-align: left;">POLYGON ((113.2621 25.68394…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yongxing</td>
<td style="text-align: right;">31689.20</td>
<td style="text-align: right;">32682.83</td>
<td style="text-align: left;">POLYGON ((113.3169 26.41843…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zixing</td>
<td style="text-align: right;">20269.00</td>
<td style="text-align: right;">25948.62</td>
<td style="text-align: left;">POLYGON ((113.7311 26.16259…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Changning</td>
<td style="text-align: right;">23901.60</td>
<td style="text-align: right;">23987.67</td>
<td style="text-align: left;">POLYGON ((112.6144 26.60198…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hengdong</td>
<td style="text-align: right;">25126.17</td>
<td style="text-align: right;">25463.14</td>
<td style="text-align: left;">POLYGON ((113.1056 27.21007…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hengnan</td>
<td style="text-align: right;">21903.43</td>
<td style="text-align: right;">21904.38</td>
<td style="text-align: left;">POLYGON ((112.7599 26.98149…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hengshan</td>
<td style="text-align: right;">22718.60</td>
<td style="text-align: right;">23127.50</td>
<td style="text-align: left;">POLYGON ((112.607 27.4689, …</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leiyang</td>
<td style="text-align: right;">25918.80</td>
<td style="text-align: right;">25949.83</td>
<td style="text-align: left;">POLYGON ((112.9996 26.69276…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Qidong</td>
<td style="text-align: right;">20307.00</td>
<td style="text-align: right;">20018.75</td>
<td style="text-align: left;">POLYGON ((111.7818 27.0383,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chenxi</td>
<td style="text-align: right;">20023.80</td>
<td style="text-align: right;">19524.17</td>
<td style="text-align: left;">POLYGON ((110.2624 28.21778…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zhongfang</td>
<td style="text-align: right;">16576.80</td>
<td style="text-align: right;">18955.00</td>
<td style="text-align: left;">POLYGON ((109.9431 27.72858…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Huitong</td>
<td style="text-align: right;">18667.00</td>
<td style="text-align: right;">17800.40</td>
<td style="text-align: left;">POLYGON ((109.9419 27.10512…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jingzhou</td>
<td style="text-align: right;">14394.67</td>
<td style="text-align: right;">15883.00</td>
<td style="text-align: left;">POLYGON ((109.8186 26.75842…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mayang</td>
<td style="text-align: right;">19848.80</td>
<td style="text-align: right;">18831.33</td>
<td style="text-align: left;">POLYGON ((109.795 27.98008,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tongdao</td>
<td style="text-align: right;">15516.33</td>
<td style="text-align: right;">14832.50</td>
<td style="text-align: left;">POLYGON ((109.9294 26.46561…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xinhuang</td>
<td style="text-align: right;">20518.00</td>
<td style="text-align: right;">17965.00</td>
<td style="text-align: left;">POLYGON ((109.227 27.43733,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xupu</td>
<td style="text-align: right;">17572.00</td>
<td style="text-align: right;">17159.89</td>
<td style="text-align: left;">POLYGON ((110.7189 28.30485…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yuanling</td>
<td style="text-align: right;">15200.12</td>
<td style="text-align: right;">16199.44</td>
<td style="text-align: left;">POLYGON ((110.9652 28.99895…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zhijiang</td>
<td style="text-align: right;">18413.80</td>
<td style="text-align: right;">18764.50</td>
<td style="text-align: left;">POLYGON ((109.8818 27.60661…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lengshuijiang</td>
<td style="text-align: right;">14419.33</td>
<td style="text-align: right;">26878.75</td>
<td style="text-align: left;">POLYGON ((111.5307 27.81472…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shuangfeng</td>
<td style="text-align: right;">24094.50</td>
<td style="text-align: right;">23188.86</td>
<td style="text-align: left;">POLYGON ((112.263 27.70421,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xinhua</td>
<td style="text-align: right;">22019.83</td>
<td style="text-align: right;">20788.14</td>
<td style="text-align: left;">POLYGON ((111.3345 28.19642…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chengbu</td>
<td style="text-align: right;">12923.50</td>
<td style="text-align: right;">12365.20</td>
<td style="text-align: left;">POLYGON ((110.4455 26.69317…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dongan</td>
<td style="text-align: right;">14756.00</td>
<td style="text-align: right;">15985.00</td>
<td style="text-align: left;">POLYGON ((111.4531 26.86812…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dongkou</td>
<td style="text-align: right;">13869.80</td>
<td style="text-align: right;">13764.83</td>
<td style="text-align: left;">POLYGON ((110.6622 27.37305…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Longhui</td>
<td style="text-align: right;">12296.67</td>
<td style="text-align: right;">11907.43</td>
<td style="text-align: left;">POLYGON ((110.985 27.65983,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shaodong</td>
<td style="text-align: right;">15775.17</td>
<td style="text-align: right;">17128.14</td>
<td style="text-align: left;">POLYGON ((111.9054 27.40254…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Suining</td>
<td style="text-align: right;">14382.86</td>
<td style="text-align: right;">14593.62</td>
<td style="text-align: left;">POLYGON ((110.389 27.10006,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wugang</td>
<td style="text-align: right;">11566.33</td>
<td style="text-align: right;">11644.29</td>
<td style="text-align: left;">POLYGON ((110.9878 27.03345…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xinning</td>
<td style="text-align: right;">13199.50</td>
<td style="text-align: right;">12706.00</td>
<td style="text-align: left;">POLYGON ((111.0736 26.84627…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xinshao</td>
<td style="text-align: right;">23412.00</td>
<td style="text-align: right;">21712.29</td>
<td style="text-align: left;">POLYGON ((111.6013 27.58275…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shaoshan</td>
<td style="text-align: right;">39541.00</td>
<td style="text-align: right;">43548.25</td>
<td style="text-align: left;">POLYGON ((112.5391 27.97742…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xiangxiang</td>
<td style="text-align: right;">36186.60</td>
<td style="text-align: right;">35049.00</td>
<td style="text-align: left;">POLYGON ((112.4549 28.05783…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baojing</td>
<td style="text-align: right;">16559.60</td>
<td style="text-align: right;">16226.83</td>
<td style="text-align: left;">POLYGON ((109.7015 28.82844…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fenghuang</td>
<td style="text-align: right;">20772.50</td>
<td style="text-align: right;">19294.40</td>
<td style="text-align: left;">POLYGON ((109.5239 28.19206…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guzhang</td>
<td style="text-align: right;">19471.20</td>
<td style="text-align: right;">18156.00</td>
<td style="text-align: left;">POLYGON ((109.8968 28.74034…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Huayuan</td>
<td style="text-align: right;">19827.33</td>
<td style="text-align: right;">19954.75</td>
<td style="text-align: left;">POLYGON ((109.5647 28.61712…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jishou</td>
<td style="text-align: right;">15466.80</td>
<td style="text-align: right;">18145.17</td>
<td style="text-align: left;">POLYGON ((109.8375 28.4696,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Longshan</td>
<td style="text-align: right;">12925.67</td>
<td style="text-align: right;">12132.75</td>
<td style="text-align: left;">POLYGON ((109.6337 29.62521…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Luxi</td>
<td style="text-align: right;">18577.17</td>
<td style="text-align: right;">18419.29</td>
<td style="text-align: left;">POLYGON ((110.1067 28.41835…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yongshun</td>
<td style="text-align: right;">14943.00</td>
<td style="text-align: right;">14050.83</td>
<td style="text-align: left;">POLYGON ((110.0003 29.29499…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anhua</td>
<td style="text-align: right;">24913.00</td>
<td style="text-align: right;">23619.75</td>
<td style="text-align: left;">POLYGON ((111.6034 28.63716…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nan</td>
<td style="text-align: right;">25093.00</td>
<td style="text-align: right;">24552.71</td>
<td style="text-align: left;">POLYGON ((112.3232 29.46074…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yuanjiang</td>
<td style="text-align: right;">24428.80</td>
<td style="text-align: right;">24733.67</td>
<td style="text-align: left;">POLYGON ((112.4391 29.1791,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jianghua</td>
<td style="text-align: right;">17003.00</td>
<td style="text-align: right;">16762.60</td>
<td style="text-align: left;">POLYGON ((111.6461 25.29661…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lanshan</td>
<td style="text-align: right;">21143.75</td>
<td style="text-align: right;">20932.60</td>
<td style="text-align: left;">POLYGON ((112.2286 25.61123…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ningyuan</td>
<td style="text-align: right;">20435.00</td>
<td style="text-align: right;">19467.75</td>
<td style="text-align: left;">POLYGON ((112.0715 26.09892…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shuangpai</td>
<td style="text-align: right;">17131.33</td>
<td style="text-align: right;">18334.00</td>
<td style="text-align: left;">POLYGON ((111.8864 26.11957…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xintian</td>
<td style="text-align: right;">24569.75</td>
<td style="text-align: right;">22541.00</td>
<td style="text-align: left;">POLYGON ((112.2578 26.0796,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Huarong</td>
<td style="text-align: right;">23835.50</td>
<td style="text-align: right;">26028.00</td>
<td style="text-align: left;">POLYGON ((112.9242 29.69134…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linxiang</td>
<td style="text-align: right;">26360.00</td>
<td style="text-align: right;">29128.50</td>
<td style="text-align: left;">POLYGON ((113.5502 29.67418…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Miluo</td>
<td style="text-align: right;">47383.40</td>
<td style="text-align: right;">46569.00</td>
<td style="text-align: left;">POLYGON ((112.9902 29.02139…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pingjiang</td>
<td style="text-align: right;">55157.75</td>
<td style="text-align: right;">47576.60</td>
<td style="text-align: left;">POLYGON ((113.8436 29.06152…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xiangyin</td>
<td style="text-align: right;">37058.00</td>
<td style="text-align: right;">36545.50</td>
<td style="text-align: left;">POLYGON ((112.9173 28.98264…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cili</td>
<td style="text-align: right;">21546.67</td>
<td style="text-align: right;">20838.50</td>
<td style="text-align: left;">POLYGON ((110.8822 29.69017…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chaling</td>
<td style="text-align: right;">23348.67</td>
<td style="text-align: right;">22531.00</td>
<td style="text-align: left;">POLYGON ((113.7666 27.10573…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Liling</td>
<td style="text-align: right;">42323.67</td>
<td style="text-align: right;">42115.50</td>
<td style="text-align: left;">POLYGON ((113.5673 27.94346…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yanling</td>
<td style="text-align: right;">28938.60</td>
<td style="text-align: right;">27619.00</td>
<td style="text-align: left;">POLYGON ((113.9292 26.6154,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">You</td>
<td style="text-align: right;">25880.80</td>
<td style="text-align: right;">27611.33</td>
<td style="text-align: left;">POLYGON ((113.5879 27.41324…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zhuzhou</td>
<td style="text-align: right;">47345.67</td>
<td style="text-align: right;">44523.29</td>
<td style="text-align: left;">POLYGON ((113.2493 28.02411…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sangzhi</td>
<td style="text-align: right;">18711.33</td>
<td style="text-align: right;">18127.43</td>
<td style="text-align: left;">POLYGON ((110.556 29.40543,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yueyang</td>
<td style="text-align: right;">29087.29</td>
<td style="text-align: right;">28746.38</td>
<td style="text-align: left;">POLYGON ((113.343 29.61064,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Qiyang</td>
<td style="text-align: right;">20748.29</td>
<td style="text-align: right;">20734.50</td>
<td style="text-align: left;">POLYGON ((111.5563 26.81318…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taojiang</td>
<td style="text-align: right;">35933.71</td>
<td style="text-align: right;">33880.62</td>
<td style="text-align: left;">POLYGON ((112.0508 28.67265…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shaoyang</td>
<td style="text-align: right;">15439.71</td>
<td style="text-align: right;">14716.38</td>
<td style="text-align: left;">POLYGON ((111.5013 27.30207…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lianyuan</td>
<td style="text-align: right;">29787.50</td>
<td style="text-align: right;">28516.22</td>
<td style="text-align: left;">POLYGON ((111.6789 28.02946…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hongjiang</td>
<td style="text-align: right;">18145.00</td>
<td style="text-align: right;">18086.14</td>
<td style="text-align: left;">POLYGON ((110.1441 27.47513…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hengyang</td>
<td style="text-align: right;">21617.00</td>
<td style="text-align: right;">21244.50</td>
<td style="text-align: left;">POLYGON ((112.7144 26.98613…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guiyang</td>
<td style="text-align: right;">29203.89</td>
<td style="text-align: right;">29568.80</td>
<td style="text-align: left;">POLYGON ((113.0811 26.04963…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Changsha</td>
<td style="text-align: right;">41363.67</td>
<td style="text-align: right;">48119.71</td>
<td style="text-align: left;">POLYGON ((112.9421 28.03722…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taoyuan</td>
<td style="text-align: right;">22259.09</td>
<td style="text-align: right;">22310.75</td>
<td style="text-align: left;">POLYGON ((112.0612 29.32855…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xiangtan</td>
<td style="text-align: right;">44939.56</td>
<td style="text-align: right;">43151.60</td>
<td style="text-align: left;">POLYGON ((113.0426 27.8942,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dao</td>
<td style="text-align: right;">16902.00</td>
<td style="text-align: right;">17133.40</td>
<td style="text-align: left;">POLYGON ((111.498 25.81679,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jiangyong</td>
<td style="text-align: right;">16930.00</td>
<td style="text-align: right;">17009.33</td>
<td style="text-align: left;">POLYGON ((111.3659 25.39472…</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Lastly,&nbsp;<em>qtm()</em>&nbsp;of&nbsp;<strong>tmap</strong>&nbsp;package is used to plot the lag_gdppc and w_ave_gdppc maps next to each other for quick comparison.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>w_avg_gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"lag_window_avg GDPPC"</span>)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(lag_gdppc, w_avg_gdppc, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="handsonex2_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="spatial-window-sum" class="level3">
<h3 class="anchored" data-anchor-id="spatial-window-sum">Spatial window sum</h3>
<p>The spatial window sum is the counter part of the window average, but without using row-standardized weights.</p>
<p>To add the diagonal element to the neighbour list, we just need to use <em>include.self()</em> from <strong>spdep</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>wm_qs <span class="ot">&lt;-</span> <span class="fu">include.self</span>(wm_q)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>wm_qs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 88 
Number of nonzero links: 536 
Percentage nonzero weights: 6.921488 
Average number of links: 6.090909 </code></pre>
</div>
</div>
<p>Next, we will assign binary weights to the neighbour structure that includes the diagonal element.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>b_weights <span class="ot">&lt;-</span> <span class="fu">lapply</span>(wm_qs, <span class="cf">function</span>(x) <span class="dv">0</span><span class="sc">*</span>x <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>b_weights[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 1 1 1 1 1 1</code></pre>
</div>
</div>
<p>Notice that now [1] has six neighbours instead of five.</p>
<p>Again, we use <em>nb2listw()</em> and <em>glist()</em> to explicitly assign weight values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>b_weights2 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_qs, </span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">glist =</span> b_weights, </span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">style =</span> <span class="st">"B"</span>)</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>b_weights2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 88 
Number of nonzero links: 536 
Percentage nonzero weights: 6.921488 
Average number of links: 6.090909 

Weights style: B 
Weights constants summary:
   n   nn  S0   S1    S2
B 88 7744 536 1072 14160</code></pre>
</div>
</div>
<p>With our new weight structure, we can compute the lag variable with&nbsp;<em>lag.listw()</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>w_sum_gdppc <span class="ot">&lt;-</span> <span class="fu">list</span>(hunan<span class="sc">$</span>NAME_3, <span class="fu">lag.listw</span>(b_weights2, hunan<span class="sc">$</span>GDPPC))</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>w_sum_gdppc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
 [1] "Anxiang"       "Hanshou"       "Jinshi"        "Li"           
 [5] "Linli"         "Shimen"        "Liuyang"       "Ningxiang"    
 [9] "Wangcheng"     "Anren"         "Guidong"       "Jiahe"        
[13] "Linwu"         "Rucheng"       "Yizhang"       "Yongxing"     
[17] "Zixing"        "Changning"     "Hengdong"      "Hengnan"      
[21] "Hengshan"      "Leiyang"       "Qidong"        "Chenxi"       
[25] "Zhongfang"     "Huitong"       "Jingzhou"      "Mayang"       
[29] "Tongdao"       "Xinhuang"      "Xupu"          "Yuanling"     
[33] "Zhijiang"      "Lengshuijiang" "Shuangfeng"    "Xinhua"       
[37] "Chengbu"       "Dongan"        "Dongkou"       "Longhui"      
[41] "Shaodong"      "Suining"       "Wugang"        "Xinning"      
[45] "Xinshao"       "Shaoshan"      "Xiangxiang"    "Baojing"      
[49] "Fenghuang"     "Guzhang"       "Huayuan"       "Jishou"       
[53] "Longshan"      "Luxi"          "Yongshun"      "Anhua"        
[57] "Nan"           "Yuanjiang"     "Jianghua"      "Lanshan"      
[61] "Ningyuan"      "Shuangpai"     "Xintian"       "Huarong"      
[65] "Linxiang"      "Miluo"         "Pingjiang"     "Xiangyin"     
[69] "Cili"          "Chaling"       "Liling"        "Yanling"      
[73] "You"           "Zhuzhou"       "Sangzhi"       "Yueyang"      
[77] "Qiyang"        "Taojiang"      "Shaoyang"      "Lianyuan"     
[81] "Hongjiang"     "Hengyang"      "Guiyang"       "Changsha"     
[85] "Taoyuan"       "Xiangtan"      "Dao"           "Jiangyong"    

[[2]]
 [1] 147903 134605 131165 135423 134635 133381 238106 297281 344573 268982
[11] 106510 136141 126832 103303 151645 196097 207589 143926 178242 175235
[21] 138765 155699 160150 117145 113730  89002  63532 112988  59330  35930
[31] 154439 145795 112587 107515 162322 145517  61826  79925  82589  83352
[41] 119897 116749  81510  63530 151986 174193 210294  97361  96472 108936
[51]  79819 108871  48531 128935  84305 188958 171869 148402  83813 104663
[61] 155742  73336 112705  78084  58257 279414 237883 219273  83354  90124
[71] 168462 165714 165668 311663 126892 229971 165876 271045 117731 256646
[81] 126603 127467 295688 336838 267729 431516  85667  51028</code></pre>
</div>
</div>
<p>Next, we will convert the lag variable listw object into a data.frame by using&nbsp;<em>as.data.frame()</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>w_sum_gdppc.res <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(w_sum_gdppc)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(w_sum_gdppc.res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"NAME_3"</span>, <span class="st">"w_sum GDPPC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note: The second command line on the code chunk above renames the field names of <em>w_sum_gdppc.res</em> object into <em>NAME_3</em> and <em>w_sum GDPPC</em> respectively.</p>
<p>Next, the code chunk below will be used to append <em>w_sum GDPPC</em> values onto <em>hunan</em> sf data.frame by using <em>left_join()</em> of <strong>dplyr</strong> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>hunan <span class="ot">&lt;-</span> <span class="fu">left_join</span>(hunan, w_sum_gdppc.res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To compare the values of lag GDPPC and Spatial window average,&nbsp;<code>kable()</code>&nbsp;of Knitr package is used to prepare a table using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>hunan <span class="sc">%&gt;%</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"County"</span>, <span class="st">"lag_sum GDPPC"</span>, <span class="st">"w_sum GDPPC"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">lag_sum GDPPC</th>
<th style="text-align: right;">w_sum GDPPC</th>
<th style="text-align: left;">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anxiang</td>
<td style="text-align: right;">124236</td>
<td style="text-align: right;">147903</td>
<td style="text-align: left;">POLYGON ((112.0625 29.75523…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hanshou</td>
<td style="text-align: right;">113624</td>
<td style="text-align: right;">134605</td>
<td style="text-align: left;">POLYGON ((112.2288 29.11684…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jinshi</td>
<td style="text-align: right;">96573</td>
<td style="text-align: right;">131165</td>
<td style="text-align: left;">POLYGON ((111.8927 29.6013,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Li</td>
<td style="text-align: right;">110950</td>
<td style="text-align: right;">135423</td>
<td style="text-align: left;">POLYGON ((111.3731 29.94649…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linli</td>
<td style="text-align: right;">109081</td>
<td style="text-align: right;">134635</td>
<td style="text-align: left;">POLYGON ((111.6324 29.76288…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shimen</td>
<td style="text-align: right;">106244</td>
<td style="text-align: right;">133381</td>
<td style="text-align: left;">POLYGON ((110.8825 30.11675…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Liuyang</td>
<td style="text-align: right;">174988</td>
<td style="text-align: right;">238106</td>
<td style="text-align: left;">POLYGON ((113.9905 28.5682,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ningxiang</td>
<td style="text-align: right;">235079</td>
<td style="text-align: right;">297281</td>
<td style="text-align: left;">POLYGON ((112.7181 28.38299…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wangcheng</td>
<td style="text-align: right;">273907</td>
<td style="text-align: right;">344573</td>
<td style="text-align: left;">POLYGON ((112.7914 28.52688…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anren</td>
<td style="text-align: right;">256221</td>
<td style="text-align: right;">268982</td>
<td style="text-align: left;">POLYGON ((113.1757 26.82734…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guidong</td>
<td style="text-align: right;">98013</td>
<td style="text-align: right;">106510</td>
<td style="text-align: left;">POLYGON ((114.1799 26.20117…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jiahe</td>
<td style="text-align: right;">104050</td>
<td style="text-align: right;">136141</td>
<td style="text-align: left;">POLYGON ((112.4425 25.74358…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linwu</td>
<td style="text-align: right;">102846</td>
<td style="text-align: right;">126832</td>
<td style="text-align: left;">POLYGON ((112.5914 25.55143…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rucheng</td>
<td style="text-align: right;">92017</td>
<td style="text-align: right;">103303</td>
<td style="text-align: left;">POLYGON ((113.6759 25.87578…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yizhang</td>
<td style="text-align: right;">133831</td>
<td style="text-align: right;">151645</td>
<td style="text-align: left;">POLYGON ((113.2621 25.68394…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yongxing</td>
<td style="text-align: right;">158446</td>
<td style="text-align: right;">196097</td>
<td style="text-align: left;">POLYGON ((113.3169 26.41843…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zixing</td>
<td style="text-align: right;">141883</td>
<td style="text-align: right;">207589</td>
<td style="text-align: left;">POLYGON ((113.7311 26.16259…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Changning</td>
<td style="text-align: right;">119508</td>
<td style="text-align: right;">143926</td>
<td style="text-align: left;">POLYGON ((112.6144 26.60198…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hengdong</td>
<td style="text-align: right;">150757</td>
<td style="text-align: right;">178242</td>
<td style="text-align: left;">POLYGON ((113.1056 27.21007…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hengnan</td>
<td style="text-align: right;">153324</td>
<td style="text-align: right;">175235</td>
<td style="text-align: left;">POLYGON ((112.7599 26.98149…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hengshan</td>
<td style="text-align: right;">113593</td>
<td style="text-align: right;">138765</td>
<td style="text-align: left;">POLYGON ((112.607 27.4689, …</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leiyang</td>
<td style="text-align: right;">129594</td>
<td style="text-align: right;">155699</td>
<td style="text-align: left;">POLYGON ((112.9996 26.69276…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Qidong</td>
<td style="text-align: right;">142149</td>
<td style="text-align: right;">160150</td>
<td style="text-align: left;">POLYGON ((111.7818 27.0383,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chenxi</td>
<td style="text-align: right;">100119</td>
<td style="text-align: right;">117145</td>
<td style="text-align: left;">POLYGON ((110.2624 28.21778…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zhongfang</td>
<td style="text-align: right;">82884</td>
<td style="text-align: right;">113730</td>
<td style="text-align: left;">POLYGON ((109.9431 27.72858…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Huitong</td>
<td style="text-align: right;">74668</td>
<td style="text-align: right;">89002</td>
<td style="text-align: left;">POLYGON ((109.9419 27.10512…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jingzhou</td>
<td style="text-align: right;">43184</td>
<td style="text-align: right;">63532</td>
<td style="text-align: left;">POLYGON ((109.8186 26.75842…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mayang</td>
<td style="text-align: right;">99244</td>
<td style="text-align: right;">112988</td>
<td style="text-align: left;">POLYGON ((109.795 27.98008,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tongdao</td>
<td style="text-align: right;">46549</td>
<td style="text-align: right;">59330</td>
<td style="text-align: left;">POLYGON ((109.9294 26.46561…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xinhuang</td>
<td style="text-align: right;">20518</td>
<td style="text-align: right;">35930</td>
<td style="text-align: left;">POLYGON ((109.227 27.43733,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xupu</td>
<td style="text-align: right;">140576</td>
<td style="text-align: right;">154439</td>
<td style="text-align: left;">POLYGON ((110.7189 28.30485…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yuanling</td>
<td style="text-align: right;">121601</td>
<td style="text-align: right;">145795</td>
<td style="text-align: left;">POLYGON ((110.9652 28.99895…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zhijiang</td>
<td style="text-align: right;">92069</td>
<td style="text-align: right;">112587</td>
<td style="text-align: left;">POLYGON ((109.8818 27.60661…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lengshuijiang</td>
<td style="text-align: right;">43258</td>
<td style="text-align: right;">107515</td>
<td style="text-align: left;">POLYGON ((111.5307 27.81472…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shuangfeng</td>
<td style="text-align: right;">144567</td>
<td style="text-align: right;">162322</td>
<td style="text-align: left;">POLYGON ((112.263 27.70421,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xinhua</td>
<td style="text-align: right;">132119</td>
<td style="text-align: right;">145517</td>
<td style="text-align: left;">POLYGON ((111.3345 28.19642…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chengbu</td>
<td style="text-align: right;">51694</td>
<td style="text-align: right;">61826</td>
<td style="text-align: left;">POLYGON ((110.4455 26.69317…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dongan</td>
<td style="text-align: right;">59024</td>
<td style="text-align: right;">79925</td>
<td style="text-align: left;">POLYGON ((111.4531 26.86812…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dongkou</td>
<td style="text-align: right;">69349</td>
<td style="text-align: right;">82589</td>
<td style="text-align: left;">POLYGON ((110.6622 27.37305…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Longhui</td>
<td style="text-align: right;">73780</td>
<td style="text-align: right;">83352</td>
<td style="text-align: left;">POLYGON ((110.985 27.65983,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shaodong</td>
<td style="text-align: right;">94651</td>
<td style="text-align: right;">119897</td>
<td style="text-align: left;">POLYGON ((111.9054 27.40254…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Suining</td>
<td style="text-align: right;">100680</td>
<td style="text-align: right;">116749</td>
<td style="text-align: left;">POLYGON ((110.389 27.10006,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wugang</td>
<td style="text-align: right;">69398</td>
<td style="text-align: right;">81510</td>
<td style="text-align: left;">POLYGON ((110.9878 27.03345…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xinning</td>
<td style="text-align: right;">52798</td>
<td style="text-align: right;">63530</td>
<td style="text-align: left;">POLYGON ((111.0736 26.84627…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xinshao</td>
<td style="text-align: right;">140472</td>
<td style="text-align: right;">151986</td>
<td style="text-align: left;">POLYGON ((111.6013 27.58275…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shaoshan</td>
<td style="text-align: right;">118623</td>
<td style="text-align: right;">174193</td>
<td style="text-align: left;">POLYGON ((112.5391 27.97742…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xiangxiang</td>
<td style="text-align: right;">180933</td>
<td style="text-align: right;">210294</td>
<td style="text-align: left;">POLYGON ((112.4549 28.05783…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baojing</td>
<td style="text-align: right;">82798</td>
<td style="text-align: right;">97361</td>
<td style="text-align: left;">POLYGON ((109.7015 28.82844…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fenghuang</td>
<td style="text-align: right;">83090</td>
<td style="text-align: right;">96472</td>
<td style="text-align: left;">POLYGON ((109.5239 28.19206…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guzhang</td>
<td style="text-align: right;">97356</td>
<td style="text-align: right;">108936</td>
<td style="text-align: left;">POLYGON ((109.8968 28.74034…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Huayuan</td>
<td style="text-align: right;">59482</td>
<td style="text-align: right;">79819</td>
<td style="text-align: left;">POLYGON ((109.5647 28.61712…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jishou</td>
<td style="text-align: right;">77334</td>
<td style="text-align: right;">108871</td>
<td style="text-align: left;">POLYGON ((109.8375 28.4696,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Longshan</td>
<td style="text-align: right;">38777</td>
<td style="text-align: right;">48531</td>
<td style="text-align: left;">POLYGON ((109.6337 29.62521…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Luxi</td>
<td style="text-align: right;">111463</td>
<td style="text-align: right;">128935</td>
<td style="text-align: left;">POLYGON ((110.1067 28.41835…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yongshun</td>
<td style="text-align: right;">74715</td>
<td style="text-align: right;">84305</td>
<td style="text-align: left;">POLYGON ((110.0003 29.29499…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anhua</td>
<td style="text-align: right;">174391</td>
<td style="text-align: right;">188958</td>
<td style="text-align: left;">POLYGON ((111.6034 28.63716…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nan</td>
<td style="text-align: right;">150558</td>
<td style="text-align: right;">171869</td>
<td style="text-align: left;">POLYGON ((112.3232 29.46074…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yuanjiang</td>
<td style="text-align: right;">122144</td>
<td style="text-align: right;">148402</td>
<td style="text-align: left;">POLYGON ((112.4391 29.1791,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jianghua</td>
<td style="text-align: right;">68012</td>
<td style="text-align: right;">83813</td>
<td style="text-align: left;">POLYGON ((111.6461 25.29661…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lanshan</td>
<td style="text-align: right;">84575</td>
<td style="text-align: right;">104663</td>
<td style="text-align: left;">POLYGON ((112.2286 25.61123…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ningyuan</td>
<td style="text-align: right;">143045</td>
<td style="text-align: right;">155742</td>
<td style="text-align: left;">POLYGON ((112.0715 26.09892…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shuangpai</td>
<td style="text-align: right;">51394</td>
<td style="text-align: right;">73336</td>
<td style="text-align: left;">POLYGON ((111.8864 26.11957…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xintian</td>
<td style="text-align: right;">98279</td>
<td style="text-align: right;">112705</td>
<td style="text-align: left;">POLYGON ((112.2578 26.0796,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Huarong</td>
<td style="text-align: right;">47671</td>
<td style="text-align: right;">78084</td>
<td style="text-align: left;">POLYGON ((112.9242 29.69134…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linxiang</td>
<td style="text-align: right;">26360</td>
<td style="text-align: right;">58257</td>
<td style="text-align: left;">POLYGON ((113.5502 29.67418…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Miluo</td>
<td style="text-align: right;">236917</td>
<td style="text-align: right;">279414</td>
<td style="text-align: left;">POLYGON ((112.9902 29.02139…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pingjiang</td>
<td style="text-align: right;">220631</td>
<td style="text-align: right;">237883</td>
<td style="text-align: left;">POLYGON ((113.8436 29.06152…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xiangyin</td>
<td style="text-align: right;">185290</td>
<td style="text-align: right;">219273</td>
<td style="text-align: left;">POLYGON ((112.9173 28.98264…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cili</td>
<td style="text-align: right;">64640</td>
<td style="text-align: right;">83354</td>
<td style="text-align: left;">POLYGON ((110.8822 29.69017…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chaling</td>
<td style="text-align: right;">70046</td>
<td style="text-align: right;">90124</td>
<td style="text-align: left;">POLYGON ((113.7666 27.10573…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Liling</td>
<td style="text-align: right;">126971</td>
<td style="text-align: right;">168462</td>
<td style="text-align: left;">POLYGON ((113.5673 27.94346…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yanling</td>
<td style="text-align: right;">144693</td>
<td style="text-align: right;">165714</td>
<td style="text-align: left;">POLYGON ((113.9292 26.6154,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">You</td>
<td style="text-align: right;">129404</td>
<td style="text-align: right;">165668</td>
<td style="text-align: left;">POLYGON ((113.5879 27.41324…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zhuzhou</td>
<td style="text-align: right;">284074</td>
<td style="text-align: right;">311663</td>
<td style="text-align: left;">POLYGON ((113.2493 28.02411…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sangzhi</td>
<td style="text-align: right;">112268</td>
<td style="text-align: right;">126892</td>
<td style="text-align: left;">POLYGON ((110.556 29.40543,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yueyang</td>
<td style="text-align: right;">203611</td>
<td style="text-align: right;">229971</td>
<td style="text-align: left;">POLYGON ((113.343 29.61064,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Qiyang</td>
<td style="text-align: right;">145238</td>
<td style="text-align: right;">165876</td>
<td style="text-align: left;">POLYGON ((111.5563 26.81318…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taojiang</td>
<td style="text-align: right;">251536</td>
<td style="text-align: right;">271045</td>
<td style="text-align: left;">POLYGON ((112.0508 28.67265…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shaoyang</td>
<td style="text-align: right;">108078</td>
<td style="text-align: right;">117731</td>
<td style="text-align: left;">POLYGON ((111.5013 27.30207…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lianyuan</td>
<td style="text-align: right;">238300</td>
<td style="text-align: right;">256646</td>
<td style="text-align: left;">POLYGON ((111.6789 28.02946…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hongjiang</td>
<td style="text-align: right;">108870</td>
<td style="text-align: right;">126603</td>
<td style="text-align: left;">POLYGON ((110.1441 27.47513…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hengyang</td>
<td style="text-align: right;">108085</td>
<td style="text-align: right;">127467</td>
<td style="text-align: left;">POLYGON ((112.7144 26.98613…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guiyang</td>
<td style="text-align: right;">262835</td>
<td style="text-align: right;">295688</td>
<td style="text-align: left;">POLYGON ((113.0811 26.04963…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Changsha</td>
<td style="text-align: right;">248182</td>
<td style="text-align: right;">336838</td>
<td style="text-align: left;">POLYGON ((112.9421 28.03722…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Taoyuan</td>
<td style="text-align: right;">244850</td>
<td style="text-align: right;">267729</td>
<td style="text-align: left;">POLYGON ((112.0612 29.32855…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xiangtan</td>
<td style="text-align: right;">404456</td>
<td style="text-align: right;">431516</td>
<td style="text-align: left;">POLYGON ((113.0426 27.8942,…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dao</td>
<td style="text-align: right;">67608</td>
<td style="text-align: right;">85667</td>
<td style="text-align: left;">POLYGON ((111.498 25.81679,…</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jiangyong</td>
<td style="text-align: right;">33860</td>
<td style="text-align: right;">51028</td>
<td style="text-align: left;">POLYGON ((111.3659 25.39472…</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Lastly,&nbsp;<em>qtm()</em>&nbsp;of&nbsp;<strong>tmap</strong>&nbsp;package is used to plot the lag_sum GDPPC and w_sum_gdppc maps next to each other for quick comparison.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>w_sum_gdppc <span class="ot">&lt;-</span> <span class="fu">qtm</span>(hunan, <span class="st">"w_sum GDPPC"</span>)</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(lag_sum_gdppc, w_sum_gdppc, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="handsonex2_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>